# LABELS: master=18
[p2b8]
[b32]
[e4]

#########
# clock #
#########
# setup clock and usage for 30 - 240 bpm
# this is the internal clock set by P1.1
[pot]
    pot         = P1.1
    output      = _RATE
    ledgauge    = off

# we want 1 bpm per step so we need 240 - 30  = 210 steps
[quantizer]
    input  = _RATE
    steps  = 210
    output = _RATE_Q

# here we want 30 to 240 BPM at 16th note resolution
# convert bpm to Hz by dividing by 15 (this is divide by 60 to go from bpm to bps and then multiply by 4 to get 4PPQ)
# -> 240 BPM = 16Hz; 30 BPM = 2Hz so we need to go from 2 to 16Hz
# this means we need to scale _CLK_RATE by a factor of 14Hz / 1V = 14
[lfo]
    hz     = _RATE_Q * 14 + 2
    square = _INT_CLK

# 24PPQ clock
[clocktool]
   clock    = _INT_CLK
   output   = _INT_CLK_24
   multiply = 6

########
# MIDI #
########
[midiin]
    trs        = 1
    usb        = 1
    clock      = _MIDI_CLK    # this is 4PPQ per definition
    midiclock  = _MIDI_CLK_24
    running    = _MIDI_RUN

# forward any received midi info to trs1
[midithrough]
    fromusb = 1
    fromtrs = 1
    totrs   = 1

[midiout]
    trs   = 2
    usb   = 1
    clock = _INT_CLK

###################
# clock use setup #
###################
# use button 1 on p2b8 as play/pause
# longpress to enter midi settings
# button needs to be held to make changes
[button]
    button     = B1.1
    led        = L1.1
    onvalue    = _DELAYED_CLK
    offvalue   = 0
    output     = _CLK
    longpress  = _CLK_SEL_MDE

# use this to overlay state on normal B1.2
# [logic]
#     input   = _CLK_SEL_MDE
#     negated = _NORMAL_PRESS
#
# [button]
#     select = _NORMAL_PRESS
#     button = B1.2
#     led    = _L12

[button]
    select = _CLK_SEL_MDE
    button = B1.2
    led    = _USE_MIDI_CLK
 
# add global clock delay to help sync midi
[pot]
    select      = _CLK_SEL_MDE
    pot         = P1.2
    bipolar     = _GLBL_CLK_DLY
    notch       = 0.05
    outputscale = 0.9

# set L1.2 to half brightness when midi clock is used
[switch]
    offset  = _USE_MIDI_CLK
    input1  = 0
    input2  = 0.2
    output1 = _MIDI_LED

[copy]
    input  = _MIDI_LED # + _L12 # use this to overlay LED state
    output = L1.2

# either select internal or external clock
[switch]
    input1  = _INT_CLK
    input2  = _MIDI_CLK
    offset  = _USE_MIDI_CLK
    output1 = _MASTER_CLK

[clocktool]
    clock  = _MASTER_CLK
    delay  = _GLBL_CLK_DLY
    output = _DELAYED_CLK

# output selected clock
[switch]
    input1 = _INT_CLK_24
    input2 = _MIDI_CLK_24
    offset = _USE_MIDI_CLK
    output = O8

# select output run
[switch]
    input1 = L1.1
    input2 = _MIDI_RUN
    offset = _USE_MIDI_CLK
    output = O6

###########################
# global things and modes #
###########################
# global clear
# this is to reset the full sequencer to default i.e. all the values
# as DROID tends to save the last settings so you can start fresh
[button]
    button        = B1.3
    longpresstime = 2
    longpress     = _CLR_ALL # this is to avoid accidental clearing

# alt mode selector
[button]
    button = B1.5
    led    = L1.5
    output = _ALT_MDE

# reset all button
[button]
    button        = B1.7
    longpresstime = 2
    longpress     = _RST_ALL

# mode selection
[buttongroup]
    maxactive        = 1
    minactive        = 1
    button1          = B1.4
    button2          = B1.6
    button3          = B1.8
    led1             = _GATE_MDE
    led2             = _CV_MDE
    led3             = _PERF_MDE
    selectionchanged = _MDE_SEL_CHANGE

# page buttons for encoder
[buttongroup]
    select    = _GATE_MDE + _CV_MDE
    button1   = B2.25
    button2   = B2.26
    button3   = B2.27
    button4   = B2.28
    button5   = B2.21
    button6   = B2.22
    button7   = B2.23
    button8   = B2.24
    led1      = _PAGE1
    led2      = _PAGE2
    led3      = _PAGE3
    led4      = _PAGE4
    led5      = _CLK_SET
    led6      = _GRV_SET
    led7      = _ENV_SLEWQ_P
    led8      = _LEN_SET
    longpress = _ENC_SEL_LNG

[logic]
    input   = _ENC_SEL_LNG
    negated = _ENC_SEL_SHT

# make sure led is lit when button is pressed
[copy]
    input  = _PAGE1
    output = L2.25

[copy]
    input  = _PAGE2
    output = L2.26

[copy]
    input  = _PAGE3
    output = L2.27

[copy]
    input  = _PAGE4
    output = L2.28

[copy]
    input  = _CLK_SET
    output = L2.21

[copy]
    input  = _GRV_SET
    output = L2.22

# this is only available for track 1 and 2 in gate mode
# or for all in tracks in cv mode
[logic]
    input1 = _SEL_1
    input2 = _SEL_2
    or     = _SEL_12

[logic]
    input1 = _ENV_SLEWQ_P
    input2 = _GATE_MDE
    input3 = _SEL_12
    and    = _ENV_LED

[logic]
    input1 = _ENV_SLEWQ_P
    input2 = _CV_MDE
    and    = _SLEWQP

[copy]
    input  = _ENV_LED + _SLEWQP
    output = L2.23

[copy]
    input  = _LEN_SET
    output = L2.24

# track selectors
# select between the four available algoquencers
# last row of B32
[buttongroup]
    minactive = 1
    maxactive = 4
    button1   = B2.29
    button2   = B2.30
    button3   = B2.31
    button4   = B2.32
    led1      = _SEL_1
    led2      = _SEL_2
    led3      = _SEL_3
    led4      = _SEL_4

# clear selection button
[button]
    button         = B2.20
    longpress      = _CLR_SEL
    longhpresstime = 2

[logic]
    input1 = _CLR_SEL
    input2 = _SEL_1
    and    = _CLR_1

[logic]
    input1 = _CLR_SEL
    input2 = _SEL_2
    and    = _CLR_2

[logic]
    input1 = _CLR_SEL
    input2 = _SEL_3
    and    = _CLR_3

[logic]
    input1 = _CLR_SEL
    input2 = _SEL_4
    and    = _CLR_4

# reset selection button
[button]
    button     = B2.19
    longpress  = _RST_BOTH
    shortpress = _RST_SEL

[logic]
    input1 = _RST_SEL
    input2 = _SEL_1
    and    = _RST_1

[logic]
    input1 = _RST_SEL
    input2 = _SEL_2
    and    = _RST_2

[logic]
    input1 = _RST_SEL
    input2 = _SEL_3
    and    = _RST_3

[logic]
    input1 = _RST_SEL
    input2 = _SEL_4
    and    = _RST_4

# pattern selection buttons
[button]
    button     = B2.17
    longpress  = _REROLL
    shortpress = _PRE_PTRN

[button]
    button     = B2.18
    shortpress = _NXT_PTRN

[logic]
    input1 = _PRE_PTRN
    input2 = _SEL_1
    and    = _PRE_PTRN_1

[logic]
    input1 = _PRE_PTRN
    input2 = _SEL_2
    and    = _PRE_PTRN_2

[logic]
    input1 = _PRE_PTRN
    input2 = _SEL_3
    and    = _PRE_PTRN_3

[logic]
    input1 = _PRE_PTRN
    input2 = _SEL_4
    and    = _PRE_PTRN_4

[logic]
    input1 = _NXT_PTRN
    input2 = _SEL_1
    and    = _NXT_PTRN_1

[logic]
    input1 = _NXT_PTRN
    input2 = _SEL_2
    and    = _NXT_PTRN_2

[logic]
    input1 = _NXT_PTRN
    input2 = _SEL_3
    and    = _NXT_PTRN_3

[logic]
    input1 = _NXT_PTRN
    input2 = _SEL_4
    and    = _NXT_PTRN_4
    
