# -------------------------------------------------
# cv mode slew and quantization controls
# -------------------------------------------------
[switch]
    input   = _SLEWQP
    output1 = _SELSLEWQP_1
    output2 = _SELSLEWQP_2
    output3 = _SELSLEWQP_3
    output4 = _SELSLEWQP_4
    offset  = _SEL_OFST * -1
    
# slew
[switch]
    input1 = _SLEW_1
    input2 = _SLEW_2
    input3 = _SLEW_3
    input4 = _SLEW_4
    offset = _SEL_OFST
    output = _SLEW_S

[switch]
    input1  = _SLEW_S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _SLEW_SET

[encoder]
    select       = _SLEWQP
    encoder      = E3.1
    color        = 0.6
    startvalue   = _SLEW_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _SLEW

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_1 * _SEL_GATE + _CLR_ALL
    output = _SLEW_1

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_2 * _SEL_GATE + _CLR_ALL
    output = _SLEW_2

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_3 * _SEL_GATE + _CLR_ALL
    output = _SLEW_3

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_4 * _SEL_GATE + _CLR_ALL
    output = _SLEW_4

# quantization degree
[switch]
    input1 = _QUANT_1R
    input2 = _QUANT_2R
    input3 = _QUANT_3R
    input4 = _QUANT_4R
    offset = _SEL_OFST
    output = _QUANT_S

[switch]
    input1  = _QUANT_S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _QUANT_SET

[encoder]
    select       = _SLEWQP
    encoder      = E3.2
    discrete     = 12
    color        = 0.8
    startvalue   = _QUANT_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _QUANT

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_1 * _SEL_GATE + _CLR_ALL
    output = _QUANT_1R

[copy]
    input  = _QUANT_1R - 1
    output = _QUANT_1

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_2 * _SEL_GATE + _CLR_ALL
    output = _QUANT_2R

[copy]
    input  = _QUANT_2R - 1
    output = _QUANT_2

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_3 * _SEL_GATE + _CLR_ALL
    output = _QUANT_3R

[copy]
    input  = _QUANT_3R - 1
    output = _QUANT_3

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_4 * _SEL_GATE + _CLR_ALL
    output = _QUANT_4R

[copy]
    input  = _QUANT_4R - 1
    output = _QUANT_4


# quantization root
[switch]
    input1 = _ROOT_1
    input2 = _ROOT_2
    input3 = _ROOT_3
    input4 = _ROOT_4
    offset = _SEL_OFST
    output = _ROOT_S

[switch]
    input1  = _ROOT_S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _ROOT_SET

[encoder]
    select       = _SLEWQP
    encoder      = E3.3
    discrete     = 12
    color        = 1
    startvalue   = _ROOT_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ROOT

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_1 * _SEL_GATE + _CLR_ALL
    output = _ROOT_1

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_2 * _SEL_GATE + _CLR_ALL
    output = _ROOT_2

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_3 * _SEL_GATE + _CLR_ALL
    output = _ROOT_3

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_4 * _SEL_GATE + _CLR_ALL
    output = _ROOT_4

# [encoder]
#     select   = _SLEWQP
#     encoder  = E3.4
#     led      = 0
#     override = 1
