# -------------------------------------------------
# cv mode page 2
# -------------------------------------------------
[logic]
    input1 = _CV_MDE
    input2 = _PAGE2
    and    = _CVP2

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[logic]
    input1 = _CVP2
    input2 = _SEL_1
    and    = _SELCVP2_1

[logic]
    input1 = _CVP2
    input2 = _SEL_2
    and    = _SELCVP2_2

[logic]
    input1 = _CVP2
    input2 = _SEL_3
    and    = _SELCVP2_3

[logic]
    input1 = _CVP2
    input2 = _SEL_4
    and    = _SELCVP2_4

# distribution
[switch]
    input1 = _DIST_CV1
    input2 = _DIST_CV2
    input3 = _DIST_CV3
    input4 = _DIST_CV4
    offset = _SEL_OFST
    output = _DIST_CVS

[switch]
    input1  = _DIST_CVS
    input2  = 0.5
    offset  = _CLR_TRIG
    output  = _DIST_CV_SET

[encoder]
    select     = _CVP2
    encoder    = E3.1
    color      = 0.75
    notch      = 0.1
    startvalue = _DIST_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _DIST_CV

[sample]
    input  = _DIST_CV
    gate   = _SELCVP2_1 * _SEL_GATE + _CLR_ALL
    output = _DIST_CV1

[sample]
    input  = _DIST_CV
    gate   = _SELCVP2_2 * _SEL_GATE + _CLR_ALL
    output = _DIST_CV2

[sample]
    input  = _DIST_CV
    gate   = _SELCVP2_3 * _SEL_GATE + _CLR_ALL
    output = _DIST_CV3

[sample]
    input  = _DIST_CV
    gate   = _SELCVP2_4 * _SEL_GATE + _CLR_ALL
    output = _DIST_CV4

# pitch low
[switch]
    input1 = _PLO_CV1
    input2 = _PLO_CV2
    input3 = _PLO_CV3
    input4 = _PLO_CV4
    offset = _SEL_OFST
    output = _PLO_CVS

[switch]
    input1  = _PLO_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _PLO_CV_SET

[encoder]
    select     = _CVP2
    encoder    = E3.2
    color      = 0.9
    notch      = 0.1
    startvalue = _PLO_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _PLO_CV

[sample]
    input  = _PLO_CV
    gate   = _SELCVP2_1 * _SEL_GATE + _CLR_ALL
    output = _PLO_CV1

[sample]
    input  = _PLO_CV
    gate   = _SELCVP2_2 * _SEL_GATE + _CLR_ALL
    output = _PLO_CV2

[sample]
    input  = _PLO_CV
    gate   = _SELCVP2_3 * _SEL_GATE + _CLR_ALL
    output = _PLO_CV3

[sample]
    input  = _PLO_CV
    gate   = _SELCVP2_4 * _SEL_GATE + _CLR_ALL
    output = _PLO_CV4

# pitch high
[switch]
    input1 = _PHI_CV1
    input2 = _PHI_CV2
    input3 = _PHI_CV3
    input4 = _PHI_CV4
    offset = _SEL_OFST
    output = _PHI_CVS

[switch]
    input1  = _PHI_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _PHI_CV_SET

[encoder]
    select     = _CVP2
    encoder    = E3.3
    color      = 1.1
#    startvalue = 0
    startvalue = _PHI_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _PHI_CV

[sample]
    input  = _PHI_CV
    gate   = _SELCVP2_1 * _SEL_GATE + _CLR_ALL
    output = _PHI_CV1

[sample]
    input  = _PHI_CV
    gate   = _SELCVP2_2 * _SEL_GATE + _CLR_ALL
    output = _PHI_CV2

[sample]
    input  = _PHI_CV
    gate   = _SELCVP2_3 * _SEL_GATE + _CLR_ALL
    output = _PHI_CV3

[sample]
    input  = _PHI_CV
    gate   = _SELCVP2_4 * _SEL_GATE + _CLR_ALL
    output = _PHI_CV4

# pitch resolution
[switch]
    input1 = _PRES_CV1
    input2 = _PRES_CV2
    input3 = _PRES_CV3
    input4 = _PRES_CV4
    offset = _SEL_OFST
    output = _PRES_CVS

[switch]
    input1  = _PRES_CVS
    input2  = 3
    offset  = _CLR_TRIG
    output  = _PRES_CV_SET

[encoder]
    select     = _CVP2
    encoder    = E3.4
    color      = 0.9
    discrete   = 15
    notch      = 0.1
    startvalue = _PRES_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _PRES_CV

[sample]
    input  = _PRES_CV
    gate   = _SELCVP2_1 * _SEL_GATE + _CLR_ALL
    output = _PRES_CV1

[sample]
    input  = _PRES_CV
    gate   = _SELCVP2_2 * _SEL_GATE + _CLR_ALL
    output = _PRES_CV2

[sample]
    input  = _PRES_CV
    gate   = _SELCVP2_3 * _SEL_GATE + _CLR_ALL
    output = _PRES_CV3

[sample]
    input  = _PRES_CV
    gate   = _SELCVP2_4 * _SEL_GATE + _CLR_ALL
    output = _PRES_CV4
