# -------------------------------------------------
# cv mode slew and quantization controls
# -------------------------------------------------
[logic]
    input1 = _SLEWQP
    input2 = _SEL_1
    and    = _SELSLEWQP_1

[logic]
    input1 = _SLEWQP
    input2 = _SEL_2
    and    = _SELSLEWQP_2

[logic]
    input1 = _SLEWQP
    input2 = _SEL_3
    and    = _SELSLEWQP_3

[logic]
    input1 = _SLEWQP
    input2 = _SEL_4
    and    = _SELSLEWQP_4
    
# slew
[switch]
    input1 = _SLEW_1
    input2 = _SLEW_2
    input3 = _SLEW_3
    input4 = _SLEW_4
    offset = _SEL_OFST
    output = _SLEW_SET

[encoder]
    select       = _SLEWQP
    encoder      = E3.1
#    startvalue   = 0
    color        = 0.6
    outputscale  = 0.4
    startvalue   = _SLEW_SET
    clear        = _SEL_CNG
    output       = _SLEW

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_1 * _SEL_GATE
    output = _SLEW_1

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_2 * _SEL_GATE
    output = _SLEW_2

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_3 * _SEL_GATE
    output = _SLEW_3

[sample]
    input  = _SLEW
    gate   = _SELSLEWQP_4 * _SEL_GATE
    output = _SLEW_4

# quantization degree
[switch]
    input1 = _QUANT_1
    input2 = _QUANT_2
    input3 = _QUANT_3
    input4 = _QUANT_4
    offset = _SEL_OFST
    output = _QUANT_SET

[encoder]
    select       = _SLEWQP
    encoder      = E3.2
#     startvalue   = 0
    outputoffset = -1
    discrete     = 12
    color        = 0.8
    startvalue   = _QUANT_SET
    clear        = _SEL_CNG
    output       = _QUANT

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_1 * _SEL_GATE
    output = _QUANT_1

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_2 * _SEL_GATE
    output = _QUANT_2

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_3 * _SEL_GATE
    output = _QUANT_3

[sample]
    input  = _QUANT
    gate   = _SELSLEWQP_4 * _SEL_GATE
    output = _QUANT_4

# quantization root
[switch]
    input1 = _ROOT_1
    input2 = _ROOT_2
    input3 = _ROOT_3
    input4 = _ROOT_4
    offset = _SEL_OFST
    output = _ROOT_SET

[encoder]
    select       = _SLEWQP
    encoder      = E3.3
#    startvalue   = 0
    discrete     = 12
    color        = 1
    startvalue   = _ROOT_SET
    clear        = _SEL_CNG
    output       = _ROOT

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_1 * _SEL_GATE
    output = _ROOT_1

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_2 * _SEL_GATE
    output = _ROOT_2

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_3 * _SEL_GATE
    output = _ROOT_3

[sample]
    input  = _ROOT
    gate   = _SELSLEWQP_4 * _SEL_GATE
    output = _ROOT_4

# [encoder]
#     select   = _SLEWQP
#     encoder  = E3.4
#     led      = 0
#     override = 1
