# -------------------------------------------------
# cv mode page 3
# -------------------------------------------------    
[logic]
    input1 = _CV_MDE
    input2 = _PAGE3
    input3 = _ENC_SEL_SHT
    input4 = _NRM_MDE
    and    = _CVP3

[logic]
    input1 = _CV_MDE
    input2 = _PAGE3
    input3 = _ENC_SEL_LNG
    input4 = _NRM_MDE
    and    = _CVP3L

[logic]
    input1 = _CV_MDE
    input2 = _PAGE3
    input3 = _ENC_SEL_SHT
    input4 = _ALT_MDE
    and    = _CVP3A

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[switch]
    input   = _CVP3
    output1 = _SELCVP3_1
    output2 = _SELCVP3_2
    output3 = _SELCVP3_3
    output4 = _SELCVP3_4
    offset  = _SEL_OFST

[switch]
    input   = _CVP3L
    output1 = _SELCVP3L_1
    output2 = _SELCVP3L_2
    output3 = _SELCVP3L_3
    output4 = _SELCVP3L_4
    offset  = _SEL_OFST
    
[switch]
    input   = _CVP3A
    output1 = _SELCVP3A_1
    output2 = _SELCVP3A_2
    output3 = _SELCVP3A_3
    output4 = _SELCVP3A_4
    offset  = _SEL_OFST

# fills
[switch]
    input1 = _FILL_CV1
    input2 = _FILL_CV2
    input3 = _FILL_CV3
    input4 = _FILL_CV4
    offset = _SEL_OFST
    output = _FILL_CVS

[switch]
    input1  = _FILL_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _FILL_CV_SET
    
[encoder]
    select     = _CVP3
    encoder    = E3.1
    color      = 1.1
    notch      = 0.1
    startvalue = _FILL_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _FILL_CV

[sample]
    input  = _FILL_CV
    gate   = _SELCVP3_1 * _SEL_GATE + _CLR_ALL
    output = _FILL_CV1

[sample]
    input  = _FILL_CV
    gate   = _SELCVP3_2 * _SEL_GATE + _CLR_ALL
    output = _FILL_CV2

[sample]
    input  = _FILL_CV
    gate   = _SELCVP3_3 * _SEL_GATE + _CLR_ALL
    output = _FILL_CV3

[sample]
    input  = _FILL_CV
    gate   = _SELCVP3_4 * _SEL_GATE + _CLR_ALL
    output = _FILL_CV4
    
# fill order
[switch]
    input1 = _FILLO_CV1
    input2 = _FILLO_CV2
    input3 = _FILLO_CV3
    input4 = _FILLO_CV4
    offset = _SEL_OFST
    output = _FILLO_CVS

[switch]
    input1  = _FILLO_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _FILLO_CV_SET

[encoder]
    select     = _CVP3L
    encoder    = E3.1
    color      = 1.3
    discrete   = 4
    notch      = 0.1
    startvalue = _FILLO_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _FILLO_CV

[sample]
    input  = _FILLO_CV
    gate   = _SELCVP3L_1 * _SEL_GATE + _CLR_ALL
    output = _FILLO_CV1

[sample]
    input  = _FILLO_CV
    gate   = _SELCVP3L_2 * _SEL_GATE + _CLR_ALL
    output = _FILLO_CV2

[sample]
    input  = _FILLO_CV
    gate   = _SELCVP3L_3 * _SEL_GATE + _CLR_ALL
    output = _FILLO_CV3

[sample]
    input  = _FILLO_CV
    gate   = _SELCVP3L_4 * _SEL_GATE + _CLR_ALL
    output = _FILLO_CV4

# repeats
[switch]
    input1 = _REP_CV1
    input2 = _REP_CV2
    input3 = _REP_CV3
    input4 = _REP_CV4
    offset = _SEL_OFST
    output = _REP_CVS

[switch]
    input1  = _REP_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _REP_CV_SET

[encoder]
    select     = _CVP3
    encoder     = E3.2
    color       = 0.8
    discrete    = 4
    notch       = 0.1
    startvalue = _REP_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _REP_CV

[sample]
    input  = _REP_CV
    gate   = _SELCVP3_1 * _SEL_GATE + _CLR_ALL
    output = _REP_CV1

[sample]
    input  = _REP_CV
    gate   = _SELCVP3_2 * _SEL_GATE + _CLR_ALL
    output = _REP_CV2

[sample]
    input  = _REP_CV
    gate   = _SELCVP3_3 * _SEL_GATE + _CLR_ALL
    output = _REP_CV3

[sample]
    input  = _REP_CV
    gate   = _SELCVP3_4 * _SEL_GATE + _CLR_ALL
    output = _REP_CV4

# alternate repeats
[switch]
    input1 = _AREP_CV1
    input2 = _AREP_CV2
    input3 = _AREP_CV3
    input4 = _AREP_CV4
    offset = _SEL_OFST
    output = _AREP_CVS

[switch]
    input1  = _AREP_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _AREP_CV_SET

[encoder]
    select       = _CVP3A
    encoder      = E3.2
    color        = 1.5
    discrete     = 4
    notch        = 0.1
    startvalue   = _AREP_CV_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _AREP_CV

[sample]
    input  = _AREP_CV
    gate   = _SELCVP3A_1 * _SEL_GATE + _CLR_ALL
    output = _AREP_CV1

[sample]
    input  = _AREP_CV
    gate   = _SELCVP3A_2 * _SEL_GATE + _CLR_ALL
    output = _AREP_CV2

[sample]
    input  = _AREP_CV
    gate   = _SELCVP3A_3 * _SEL_GATE + _CLR_ALL
    output = _AREP_CV3

[sample]
    input  = _AREP_CV
    gate   = _SELCVP3A_4 * _SEL_GATE + _CLR_ALL
    output = _AREP_CV4

# alternatebars
[switch]
    input1 = _ABAR_CV1
    input2 = _ABAR_CV2
    input3 = _ABAR_CV3
    input4 = _ABAR_CV4
    offset = _SEL_OFST
    output = _ABAR_CVS

[switch]
    input1  = _ABAR_CVS
    input2  = 1
    offset  = _CLR_TRIG
    output  = _ABAR_CV_SET

[encoder]
    select       = _CVP3
    encoder      = E3.3
    color        = 1.5
    discrete     = 8
    notch        = 0.1
    startvalue   = _ABAR_CV_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ABAR_CV

[sample]
    input  = _ABAR_CV
    gate   = _SELCVP3_1 * _SEL_GATE + _CLR_ALL
    output = _ABAR_CV1

[sample]
    input  = _ABAR_CV
    gate   = _SELCVP3_2 * _SEL_GATE + _CLR_ALL
    output = _ABAR_CV2

[sample]
    input  = _ABAR_CV
    gate   = _SELCVP3_3 * _SEL_GATE + _CLR_ALL
    output = _ABAR_CV3

[sample]
    input  = _ABAR_CV
    gate   = _SELCVP3_4 * _SEL_GATE + _CLR_ALL
    output = _ABAR_CV4

# morphs
[switch]
    input1 = _MOR_CV1
    input2 = _MOR_CV2
    input3 = _MOR_CV3
    input4 = _MOR_CV4
    offset = _SEL_OFST
    output = _MOR_CVS

[switch]
    input1  = _MOR_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _MOR_CV_SET

[encoder]
    select     = _CVP3
    encoder    = E3.4
    color      = 0.2
    notch      = 0.1
    startvalue = _MOR_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _MOR_CV

[sample]
    input  = _MOR_CV
    gate   = _SELCVP3_1 * _SEL_GATE + _CLR_ALL
    output = _MOR_CV1

[sample]
    input  = _MOR_CV
    gate   = _SELCVP3_2 * _SEL_GATE + _CLR_ALL
    output = _MOR_CV2

[sample]
    input  = _MOR_CV
    gate   = _SELCVP3_3 * _SEL_GATE + _CLR_ALL
    output = _MOR_CV3

[sample]
    input  = _MOR_CV
    gate   = _SELCVP3_4 * _SEL_GATE + _CLR_ALL
    output = _MOR_CV4

# branches
[switch]
    input1 = _BRN_CV1
    input2 = _BRN_CV2
    input3 = _BRN_CV3
    input4 = _BRN_CV4
    offset = _SEL_OFST
    output = _BRN_CVS

[switch]
    input1  = _BRN_CVS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _BRN_CV_SET

[encoder]
    select     = _CVP3L
    encoder    = E3.4
    color      = 0.5
    discrete   = 5
    notch      = 0.1
    startvalue = _BRN_CV_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _BRN_CV

[sample]
    input  = _BRN_CV
    gate   = _SELCVP3L_1 * _SEL_GATE + _CLR_ALL
    output = _BRN_CV1

[sample]
    input  = _BRN_CV
    gate   = _SELCVP3L_2 * _SEL_GATE + _CLR_ALL
    output = _BRN_CV2

[sample]
    input  = _BRN_CV
    gate   = _SELCVP3L_3 * _SEL_GATE + _CLR_ALL
    output = _BRN_CV3

[sample]
    input  = _BRN_CV
    gate   = _SELCVP3L_4 * _SEL_GATE + _CLR_ALL
    output = _BRN_CV4
