# LABELS: master=18
[p2b8]
[b32]
[e4]

[buttongroup]
    minactive = 1
    maxactive = 1
    button1   = B2.29
    button2   = B2.30
    button3   = B2.31
    button4   = B2.32
    led1      = _SEL_1
    led2      = _SEL_2
    led3             = _SEL_3
    led4             = _SEL_4
    output           = _SEL_OFST
    buttonpress = _SEL_CNG

[logic]
    input   = _SEL_CNG
    negated = _SEL_GATE

[copy]
    input = _SEL_1
    output = L2.29

[copy]
    input = _SEL_2
    output = L2.30

[copy]
    input = _SEL_3
    output = L2.31

[copy]
    input = _SEL_4
    output = L2.32

[switch]
    input1 = _OUT_1
    input2 = _OUT_2
    input3 = _OUT_3
    input4 = _OUT_4
    offset = _SEL_OFST
    output = _ENC_VAL

[encoder]
    encoder    = E3.1
    color      = 0.15
    notch      = 0.1
    startvalue = _ENC_VAL
    clear      = _SEL_CNG
    output = _ENC_OUT

[sample]
    input  = _ENC_OUT
    gate   = _SEL_1 * _SEL_GATE
    output = _OUT_1

[sample]
    input  = _ENC_OUT
    gate   = _SEL_2 * _SEL_GATE
    output = _OUT_2

[sample]
    input  = _ENC_OUT
    gate   = _SEL_3 * _SEL_GATE
    output = _OUT_3

[sample]
    input  = _ENC_OUT
    gate   = _SEL_4 * _SEL_GATE
    output = _OUT_4
