# -------------------------------------------------
# gates mode envelope controls
# -------------------------------------------------
# contour controls for duck of track 1 and general contour of track 2
[logic]
    input1 = _ENV_SLEWQ_P
    input2 = _GATE_MDE
    input3 = _ENC_SEL_SHT
    and    = _ENVP

[logic]
    input1 = _ENV_SLEWQ_P
    input2 = _GATE_MDE
    input3 = _ENC_SEL_LNG
    and    = _ENVPS
    
[logic]
    input1 = _ENVP
    input2 = _SEL_1
    and    = _SELEP_1

[logic]
    input1 = _ENVP
    input2 = _SEL_2
    and    = _SELEP_2

[logic]
    input1 = _ENVPS
    input2 = _SEL_1
    and    = _SELEPS_1

[logic]
    input1 = _ENVPS
    input2 = _SEL_2
    and    = _SELEPS_2

# attack time
[switch]
    input1 = _ATK_T_C1
    input2 = _ATK_T_C2
    offset = _SEL_OFST
    output = _ATK_TS

[switch]
    input1  = _ATK_TS
    input2  = 0.1 # together with scale default = 100ms
    offset  = _CLR_TRIG
    output  = _ATK_T_SET

[encoder]
    select       = _ENVP
    encoder      = E3.1
    color        = 0.2
    notch        = 0.1
    outputscale  = 10    # scale attack to 1/2 = 1s max duration see contour manual for more detail
    startvalue   = _ATK_T_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ATK_T

[sample]
    input  = _ATK_T
    gate   = _SELEP_1 * _SEL_GATE + _CLR_ALL
    output = _ATK_T_C1

[sample]
    input  = _ATK_T
    gate   = _SELEP_2 * _SEL_GATE + _CLR_ALL
    output = _ATK_T_C2

# attack shape
[switch]
    input1 = _ATK_S_C1
    input2 = _ATK_S_C2
    offset = _SEL_OFST
    output = _ATK_SS

[switch]
    input1  = _ATK_SS
    input2  = 0.5
    offset  = _CLR_TRIG
    output  = _ATK_S_SET

[encoder]
    select       = _ENVPS
    encoder      = E3.1
    color        = 0.4
    notch        = 0.1
    startvalue   = _ATK_S_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ATK_S

[sample]
    input  = _ATK_S
    gate   = _SELEPS_1 * _SEL_GATE + _CLR_ALL
    output = _ATK_S_C1

[sample]
    input  = _ATK_S
    gate   = _SELEPS_2 * _SEL_GATE + _CLR_ALL
    output = _ATK_S_C2

# hold time
[switch]
    input1 = _HLD_T_C1
    input2 = _HLD_T_C2
    offset = _SEL_OFST
    output = _HLD_TS

[switch]
    input1  = _HLD_TS
    input2  = 0.25 # corresponds to 500ms
    offset  = _CLR_TRIG
    output  = _HLD_T_SET
    
[encoder]
    select       = _ENVP
    encoder      = E3.2
    color        = 0.6
    notch        = 0.25      
    startvalue   = _HLD_T_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _HLD_T

[sample]
    input  = _HLD_T
    gate   = _SELEP_1 * _SEL_GATE + _CLR_ALL
    output = _HLD_T_C1

[sample]
    input  = _HLD_T
    gate   = _SELEP_2 * _SEL_GATE + _CLR_ALL
    output = _HLD_T_C2

# since hold has no shape we use these to deactivate the leds of the respective encoders
# [encoder]
#     select   = _ENVPS
#     encoder  = E3.2
#     led      = 0
#     override = 1

# release time
[switch]
    input1 = _REL_T_C1
    input2 = _REL_T_C2
    offset = _SEL_OFST
    output = _REL_TS
    
[switch]
    input1  = _REL_TS
    input2  = 0.05
    offset  = _CLR_TRIG
    output  = _REL_T_SET

[encoder]
    select       = _ENVP
    encoder      = E3.3
    color        = 1
    startvalue   = _REL_T_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _REL_T

[sample]
    input  = _REL_T
    gate   = _SELEP_1 * _SEL_GATE + _CLR_ALL
    output = _REL_T_C1

[sample]
    input  = _REL_T
    gate   = _SELEP_2 * _SEL_GATE + _CLR_ALL
    output = _REL_T_C2
    
# release shape
[switch]
    input1 = _REL_S_C1
    input2 = _REL_S_C2
    offset = _SEL_OFST
    output = _REL_SS

[switch]
    input1  = _REL_SS
    input2  = 0.5
    offset  = _CLR_TRIG
    output  = _REL_S_SET

[encoder]
    select       = _ENVPS
    encoder      = E3.3
    color        = 1.2
    notch        = 0.5
    startvalue   = _REL_S_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _REL_S

[sample]
    input  = _REL_S
    gate   = _SELEPS_1 * _SEL_GATE + _CLR_ALL
    output = _REL_S_C1

[sample]
    input  = _REL_S
    gate   = _SELEPS_2 * _SEL_GATE + _CLR_ALL
    output = _REL_S_C2

# attenuate contours
# by default env 1 is inverted because we use it for sidechaining
[button]
    select     = _SELEP_1
    button     = B3.4
    startvalue = -1
    onvalue    = -1
    offvalue   = 1
    clear      = _SELEP_1 * _CLR_TRIG + _CLR_ALL
    output     = _ATTN_C1_MUL
    
[button]
    select     = _SELEP_2
    button     = B3.4
    startvalue = 1
    onvalue    = -1
    offvalue   = 1
    clear      = _SELEP_2 * _CLR_TRIG + _CLR_ALL
    output     = _ATTN_C2_MUL
    
[switch]
    input1 = _ATTN_C1
    input2 = _ATTN_C2
    offset = _SEL_OFST
    output = _ATTN_S

[switch]
    input1  = _ATTN_S
    input2  = 1
    offset  = _CLR_TRIG
    output  = _ATTN_SET

[compare]
    input   = _ATTN_C1_MUL
    compare = 0
    ifless  = 0.2
    else    = 1.4
    output  = _ATTN_C1_COL

[compare]
    input   = _ATTN_C2_MUL
    compare = 0
    ifless  = 0.2
    else    = 1.4
    output  = _ATTN_C2_COL

[switch]
    input1 = _ATTN_C1_COL
    input2 = _ATTN_C2_COL
    offset = _SEL_OFST
    output = _ATTN_COL

[encoder]
    select       = _ENVP
    encoder      = E3.4
    color        = _ATTN_COL
    notch        = 0.1
    startvalue   = _ATTN_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ATTN

[sample]
    input  = _ATTN
    gate   = _SELEP_1 * _SEL_GATE + _CLR_ALL
    output = _ATTN_C1

[sample]
    input  = _ATTN
    gate   = _SELEP_2 * _SEL_GATE + _CLR_ALL
    output = _ATTN_C2
    

# show nothing on shape page
# [encoder]
#     select   = _ENVPS
#     encoder  = E3.4
#     led      = 0
#     override = 1
