# -------------------------------------------------
# gates mode page 2
# -------------------------------------------------
[logic]
    input1 = _GATE_MDE
    input2 = _PAGE2
    and    = _GP2

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[switch]
    input   = _GP2
    output1 = _SELGP2_1
    output2 = _SELGP2_2
    output3 = _SELGP2_3
    output4 = _SELGP2_4
    offset  = _SEL_OFST * -1

# distribution
[switch]
    input1 = _DIST_G1
    input2 = _DIST_G2
    input3 = _DIST_G3
    input4 = _DIST_G4
    offset = _SEL_OFST
    output = _DIST_GS

[switch]
    input1  = _DIST_GS
    input2  = 0.5
    offset  = _CLR_TRIG
    output  = _DIST_G_SET

[encoder]
    select     = _GP2
    encoder    = E3.1
    color      = 0.75
    notch      = 0.1
    startvalue = _DIST_G_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _DIST_G

[sample]
    input  = _DIST_G
    gate   = _SELGP2_1 * _SEL_GATE + _CLR_ALL
    output = _DIST_G1

[sample]
    input  = _DIST_G
    gate   = _SELGP2_2 * _SEL_GATE + _CLR_ALL
    output = _DIST_G2

[sample]
    input  = _DIST_G
    gate   = _SELGP2_3 * _SEL_GATE + _CLR_ALL
    output = _DIST_G3

[sample]
    input  = _DIST_G
    gate   = _SELGP2_4 * _SEL_GATE + _CLR_ALL
    output = _DIST_G4

# gate length
[switch]
    input1 = _GLEN_G1
    input2 = _GLEN_G2
    input3 = _GLEN_G3
    input4 = _GLEN_G4
    offset = _SEL_OFST
    output = _GLEN_GS

[switch]
    input1  = _GLEN_GS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _GLEN_G_SET

[encoder]
    select       = _GP2
    encoder      = E3.2
    color        = 0.9
    notch        = 0.1
    startvalue   = _GLEN_G_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _GLEN_G

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_1 * _SEL_GATE + _CLR_ALL
    output = _GLEN_G1

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_2 * _SEL_GATE + _CLR_ALL
    output = _GLEN_G2

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_3 * _SEL_GATE + _CLR_ALL
    output = _GLEN_G3

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_4 * _SEL_GATE + _CLR_ALL
    output = _GLEN_G4
