# -------------------------------------------------
# gates mode page 4
# -------------------------------------------------
[logic]
    input1 = _GATE_MDE
    input2 = _PAGE4
    and    = _GP4

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[switch]
    input   = _GP4
    output1 = _SELGP4_1
    output2 = _SELGP4_2
    output3 = _SELGP4_3
    output4 = _SELGP4_4
    offset  = _SEL_OFST

# rolls
[switch]
    input1 = _ROLL_G1
    input2 = _ROLL_G2
    input3 = _ROLL_G3
    input4 = _ROLL_G4
    offset = _SEL_OFST
    output = _ROLL_GS

[switch]
    input1  = _ROLL_GS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _ROLL_G_SET
    
[encoder]
    select     = _GP4
    encoder    = E3.1
    color      = 0.5
    notch      = 0.1
    startvalue = _ROLL_G_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _ROLL_G

[sample]
    input  = _ROLL_G
    gate   = _SELGP4_1 * _SEL_GATE + _CLR_ALL
    output = _ROLL_G1

[sample]
    input  = _ROLL_G
    gate   = _SELGP4_2 * _SEL_GATE + _CLR_ALL
    output = _ROLL_G2

[sample]
    input  = _ROLL_G
    gate   = _SELGP4_3 * _SEL_GATE + _CLR_ALL
    output = _ROLL_G3

[sample]
    input  = _ROLL_G
    gate   = _SELGP4_4 * _SEL_GATE + _CLR_ALL
    output = _ROLL_G4

# rollcount
[switch]
    input1 = _ROC_G1
    input2 = _ROC_G2
    input3 = _ROC_G3
    input4 = _ROC_G4
    offset = _SEL_OFST
    output = _ROC_GS

[switch]
    input1  = _ROC_GS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _ROC_G_SET

[encoder]
    select       = _GP4
    encoder      = E3.2
    color        = 0.7
    discrete     = 5
    notch        = 0.1
    startvalue   = _ROC_G_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ROC_G

[sample]
    input  = _ROC_G
    gate   = _SELGP4_1 * _SEL_GATE + _CLR_ALL
    output = _ROC_G1

[sample]
    input  = _ROC_G
    gate   = _SELGP4_2 * _SEL_GATE + _CLR_ALL
    output = _ROC_G2

[sample]
    input  = _ROC_G
    gate   = _SELGP4_3 * _SEL_GATE + _CLR_ALL
    output = _ROC_G3

[sample]
    input  = _ROC_G
    gate   = _SELGP4_4 * _SEL_GATE + _CLR_ALL
    output = _ROC_G4

# rollsteps
[switch]
    input1 = _ROS_G1
    input2 = _ROS_G2
    input3 = _ROS_G3
    input4 = _ROS_G4
    offset = _SEL_OFST
    output = _ROS_GS

[switch]
    input1  = _ROS_GS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _ROS_G_SET

[encoder]
    select       = _GP4
    encoder      = E3.3
    color        = 0.9
    discrete     = 5
    notch        = 0.1
    startvalue   = _ROS_G_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _ROS_G

[sample]
    input  = _ROS_G
    gate   = _SELGP4_1 * _SEL_GATE + _CLR_ALL
    output = _ROS_G1

[sample]
    input  = _ROS_G
    gate   = _SELGP4_2 * _SEL_GATE + _CLR_ALL
    output = _ROS_G2

[sample]
    input  = _ROS_G
    gate   = _SELGP4_3 * _SEL_GATE + _CLR_ALL
    output = _ROS_G3

[sample]
    input  = _ROS_G
    gate   = _SELGP4_4 * _SEL_GATE + _CLR_ALL
    output = _ROS_G4
