# -------------------------------------------------
# gates mode clock controlls
# -------------------------------------------------
[logic]
    input1 = _GATE_MDE
    input2 = _CLK_SET
    and    = _CLKG

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[switch]
    input   = _CLKG
    output1 = _SELCLKG_1
    output2 = _SELCLKG_2
    output3 = _SELCLKG_3
    output4 = _SELCLKG_4
    offset  = _SEL_OFST

# clock delay
[switch]
    input1 = _DLY_G1
    input2 = _DLY_G2
    input3 = _DLY_G3
    input4 = _DLY_G4
    offset = _SEL_OFST
    output = _DLY_GS

[switch]
    input1  = _DLY_GS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _DLY_G_SET

[encoder]
    select       = _CLKG
    encoder      = E3.1
    color        = 0.2
    notch        = 0.1
    mode         = 2
    startvalue   = _DLY_G_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _DLY_G

[sample]
    input  = _DLY_G
    gate   = _SELCLKG_1 * _SEL_GATE + _CLR_ALL
    output = _DLY_G1

[sample]
    input  = _DLY_G
    gate   = _SELCLKG_2 * _SEL_GATE + _CLR_ALL
    output = _DLY_G2

[sample]
    input  = _DLY_G
    gate   = _SELCLKG_3 * _SEL_GATE + _CLR_ALL
    output = _DLY_G3

[sample]
    input  = _DLY_G
    gate   = _SELCLKG_4 * _SEL_GATE + _CLR_ALL
    output = _DLY_G4

# clock division
[switch]
    input1 = _DIV_G1R
    input2 = _DIV_G2R
    input3 = _DIV_G3R
    input4 = _DIV_G4R
    offset = _SEL_OFST
    output = _DIV_GS

[switch]
    input1  = _DIV_GS
    input2  = 7
    offset  = _CLR_TRIG
    output  = _DIV_G_SET

[encoder]
    select       = _CLKG
    encoder      = E3.2
    color        = 1
    # with these setting encoder goes from -7 to +7 resting at 0
    discrete     = 15
    notch        = 0.1
    startvalue   = _DIV_G_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _DIV_G

[sample]
    input  = _DIV_G
    gate   = _SELCLKG_1 * _SEL_GATE + _CLR_ALL
    output = _DIV_G1R

# this is necessary since S&H feedback to encoder would lead to value drift
# essentially the offset would be applied again and again to the sampled value
# since we sample the output not the actual value of the encoder
# so offset needs to happen afterwards
# this is basically the same with outputscale really so we just remove those where we don't need them
[copy]
    input  = _DIV_G1R - 7
    output = _DIV_G1

[sample]
    input  = _DIV_G
    gate   = _SELCLKG_2 * _SEL_GATE + _CLR_ALL
    output = _DIV_G2R

[copy]
    input  = _DIV_G2R - 7
    output = _DIV_G2

[sample]
    input  = _DIV_G
    gate   = _SELCLKG_3 * _SEL_GATE + _CLR_ALL
    output = _DIV_G3R

[copy]
    input  = _DIV_G3R - 7
    output = _DIV_G3

[sample]
    input  = _DIV_G
    gate   = _SELCLKG_4 * _SEL_GATE + _CLR_ALL
    output = _DIV_G4R

[copy]
    input  = _DIV_G4R - 7
    output = _DIV_G4

# dont display anything here now
# [encoder]
#     select   = _CLKG
#     encoder  = E3.3
#     led      = 0
#     override = 1

# [encoder]
#     select   = _CLKG
#     encoder  = E3.4
#     led      = 0
#     override = 1

# groove or timing menu
[logic]
    input1 = _GATE_MDE * _GRV_SET
    input2 = _ENC_SEL_SHT
    and    = _GRVGP1

[logic]
    input1 = _GATE_MDE * _GRV_SET
    input2 = _ENC_SEL_LNG
    and    = _GRVGP2

[switch]
    input   = _GRVGP1
    output1 = _SELGRVGP1_1
    output2 = _SELGRVGP1_2
    output3 = _SELGRVGP1_3
    output4 = _SELGRVGP1_4
    offset  = _SEL_OFST

[switch]
    input   = _GRVGP2
    output1 = _SELGRVGP2_1
    output2 = _SELGRVGP2_2
    output3 = _SELGRVGP2_3
    output4 = _SELGRVGP2_4
    offset  = _SEL_OFST
    
[case]
    case1  = _GRVGP1
    value1 = 0.1
    case2  = _GRVGP2
    value2 = 0.3
    output = _ENC_COL_G

# groove timing 1 and 5
[switch]
    input1 = _GRV_T1_G1
    input2 = _GRV_T1_G2
    input3 = _GRV_T1_G3
    input4 = _GRV_T1_G4
    offset = _GRVGP1 * _SEL_OFST
    output = _GRVG_T1_SET

[switch]
    input1 = _GRV_T5_G1
    input2 = _GRV_T5_G2
    input3 = _GRV_T5_G3
    input4 = _GRV_T5_G4
    offset = _GRVGP2 * _SEL_OFST
    output = _GRVG_T5_SET

[case]
    case1  = _GRVGP1
    value1 = _GRVG_T1_SET
    case2  = _GRVGP2
    value2 = _GRVG_T5_SET
    output = _GRVG_15S

[switch]
    input1  = _GRVG_15S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _GRVG_15_SET

[encoder]
    select       = _GATE_MDE * _GRV_SET
    encoder      = E3.1
    color        = _ENC_COL_G * _SEL_OFST + 1
#    startvalue   = 0
    mode         = 2
    notch        = 0.1
    startvalue   = _GRVG_15_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _GRVG_15

# track 1
[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP1_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T1_G1

[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP2_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T5_G1

# track 2
[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP1_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T1_G2

[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP2_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T5_G2

# track 3
[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP1_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T1_G3

[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP2_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T5_G3

# track 4
[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP1_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T1_G4

[sample]
    input  = _GRVG_15
    gate   = _SELGRVGP2_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T5_G4

# groove timing 2 and 6
[switch]
    input1 = _GRV_T2_G1
    input2 = _GRV_T2_G2
    input3 = _GRV_T2_G3
    input4 = _GRV_T2_G4
    offset = _GRVGP1 * _SEL_OFST
    output = _GRVG_T2_SET

[switch]
    input1 = _GRV_T6_G1
    input2 = _GRV_T6_G2
    input3 = _GRV_T6_G3
    input4 = _GRV_T6_G4
    offset = _GRVGP2 * _SEL_OFST
    output = _GRVG_T6_SET

[case]
    case1  = _GRVGP1
    value1 = _GRVG_T2_SET
    case2  = _GRVGP2
    value2 = _GRVG_T6_SET
    output = _GRVG_26S

[switch]
    input1  = _GRVG_26S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _GRVG_26_SET
    
[encoder]
    select       = _GATE_MDE * _GRV_SET
    encoder      = E3.2
    color        = _ENC_COL_G * _SEL_OFST + 1
#    startvalue   = 0
    mode         = 2
    notch        = 0.1
    startvalue   = _GRVG_26_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _GRVG_26

# track 1
[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP1_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T2_G1

[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP2_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T6_G1

# track 2
[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP1_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T2_G2

[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP2_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T6_G2

# track 3
[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP1_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T2_G3

[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP2_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T6_G3

# track 4
[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP1_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T2_G4

[sample]
    input  = _GRVG_26
    gate   = _SELGRVGP2_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T6_G4

# groove timing 3 and 7
[switch]
    input1 = _GRV_T3_G1
    input2 = _GRV_T3_G2
    input3 = _GRV_T3_G3
    input4 = _GRV_T3_G4
    offset = _GRVGP1 * _SEL_OFST
    output = _GRVG_T3_SET

[switch]
    input1 = _GRV_T7_G1
    input2 = _GRV_T7_G2
    input3 = _GRV_T7_G3
    input4 = _GRV_T7_G4
    offset = _GRVGP2 * _SEL_OFST
    output = _GRVG_T7_SET

[case]
    case1  = _GRVGP1
    value1 = _GRVG_T3_SET
    case2  = _GRVGP2
    value2 = _GRVG_T7_SET
    output = _GRVG_37S

[switch]
    input1  = _GRVG_37S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _GRVG_37_SET
    
[encoder]
    select       = _GATE_MDE * _GRV_SET
    encoder      = E3.3
    color        = _ENC_COL_G * _SEL_OFST + 1
#    startvalue   = 0
    mode         = 2
    notch        = 0.1
    startvalue   = _GRVG_37_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _GRVG_37

# track 1
[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP1_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T3_G1

[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP2_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T7_G1

# track 2
[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP1_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T3_G2

[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP2_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T7_G2

# track 3
[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP1_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T3_G3

[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP2_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T7_G3

# track 4
[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP1_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T3_G4

[sample]
    input  = _GRVG_37
    gate   = _SELGRVGP2_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T7_G4

# groove timing 4 and 8
[switch]
    input1 = _GRV_T4_G1
    input2 = _GRV_T4_G2
    input3 = _GRV_T4_G3
    input4 = _GRV_T4_G4
    offset = _GRVGP1 * _SEL_OFST
    output = _GRVG_T4_SET

[switch]
    input1 = _GRV_T8_G1
    input2 = _GRV_T8_G2
    input3 = _GRV_T8_G3
    input4 = _GRV_T8_G4
    offset = _GRVGP2 * _SEL_OFST
    output = _GRVG_T8_SET

[case]
    case1 = _GRVGP1
    value1 = _GRVG_T4_SET
    case2  = _GRVGP2
    value2 = _GRVG_T8_SET
    output = _GRVG_48S

[switch]
    input1  = _GRVG_48S
    input2  = 0
    offset  = _CLR_TRIG
    output  = _GRVG_48_SET
    
[encoder]
    select       = _GATE_MDE * _GRV_SET
    encoder      = E3.4
    color        = _ENC_COL_G * _SEL_OFST + 1
#    startvalue   = 0
    mode         = 2
    notch        = 0.1
    startvalue   = _GRVG_48_SET
    clear        = _SEL_CNG + _CLR_TRIG
    output       = _GRVG_48

# track 1
[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP1_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T4_G1

[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP2_1 * _SEL_GATE + _CLR_ALL
    output = _GRV_T8_G1

# track 2
[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP1_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T4_G2

[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP2_2 * _SEL_GATE + _CLR_ALL
    output = _GRV_T8_G2

# track 3
[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP1_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T4_G3

[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP2_3 * _SEL_GATE + _CLR_ALL
    output = _GRV_T8_G3

# track 4
[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP1_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T4_G4

[sample]
    input  = _GRVG_48
    gate   = _SELGRVGP2_4 * _SEL_GATE + _CLR_ALL
    output = _GRV_T8_G4
    
