# -------------------------------------------------
# gates mode page 2
# -------------------------------------------------
[logic]
    input1 = _GATE_MDE
    input2 = _PAGE2
    and    = _GP2

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[logic]
    input1 = _GP2
    input2 = _SEL_1
    and    = _SELGP2_1

[logic]
    input1 = _GP2
    input2 = _SEL_2
    and    = _SELGP2_2

[logic]
    input1 = _GP2
    input2 = _SEL_3
    and    = _SELGP2_3

[logic]
    input1 = _GP2
    input2 = _SEL_4
    and    = _SELGP2_4

# distribution
[switch]
    input1 = _DIST_G1
    input2 = _DIST_G2
    input3 = _DIST_G3
    input4 = _DIST_G4
    offset = _SEL_OFST
    output = _DIST_G_SET

[encoder]
    select     = _GP2
    encoder    = E3.1
    color      = 0.75
#    startvalue = 0.5
    startvalue = _DIST_G_SET
    clear      = _SEL_CNG
    output     = _DIST_G

[sample]
    input  = _DIST_G
    gate   = _SELGP2_1 * _SEL_GATE
    output = _DIST_G1

[sample]
    input  = _DIST_G
    gate   = _SELGP2_2 * _SEL_GATE
    output = _DIST_G2

[sample]
    input  = _DIST_G
    gate   = _SELGP2_3 * _SEL_GATE
    output = _DIST_G3

[sample]
    input  = _DIST_G
    gate   = _SELGP2_4 * _SEL_GATE
    output = _DIST_G4

# gate length
[switch]
    input1 = _GLEN_G1
    input2 = _GLEN_G2
    input3 = _GLEN_G3
    input4 = _GLEN_G4
    offset = _SEL_OFST
    output = _GLEN_G_SET

[encoder]
    select       = _GP2
    encoder      = E3.2
    color        = 0.9
#    startvalue   = 0
    outputoffset = 0.1 # this adheres to default and enables merging of successive aka legato
    startvalue   = _GLEN_G_SET
    clear        = _SEL_CNG
    output       = _GLEN_G

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_1 * _SEL_GATE
    output = _GLEN_G1

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_2 * _SEL_GATE
    output = _GLEN_G2

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_3 * _SEL_GATE
    output = _GLEN_G3

[sample]
    input  = _GLEN_G
    gate   = _SELGP2_4 * _SEL_GATE
    output = _GLEN_G4

# dont display anything here now
# maybe better with select and copy if even necessary
# [encoder]
#     select   = _GP2
#     encoder  = E3.3
#     led      = 0
#     override = 1

# [encoder]
#     select   = _GP2
#     encoder  = E3.4
#     led      = 0
#     override = 1
