# -------------------------------------------------
# gates mode page 1
# -------------------------------------------------
[logic]
    input1 = _GATE_MDE
    input2 = _PAGE1
    and    = _GP1

# allow reset only for current page and selected tracks
# this circumvents the fact that encoder
# processes inputs even if not selected
# this is also due to the limit of math operations at inputs
[switch]
    input   = _GP1
    output1 = _SELGP1_1
    output2 = _SELGP1_2
    output3 = _SELGP1_3
    output4 = _SELGP1_4
    offset  = _SEL_OFST * -1
    
# activity
[switch]
    input1 = _ACT_G1
    input2 = _ACT_G2
    input3 = _ACT_G3
    input4 = _ACT_G4
    offset = _SEL_OFST
    output = _ACT_GS

[switch]
    input1  = _ACT_GS
    input2  = 0.5
    offset  = _CLR_TRIG
    output  = _ACT_G_SET
    
[encoder]
    select     = _GP1
    encoder    = E3.1
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_G_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _ACT_G

[sample]
    input  = _ACT_G
    gate   = _SELGP1_1 * _SEL_GATE + _CLR_ALL
    output = _ACT_G1

[sample]
    input  = _ACT_G
    gate   = _SELGP1_2 * _SEL_GATE + _CLR_ALL
    output = _ACT_G2

[sample]
    input  = _ACT_G
    gate   = _SELGP1_3 * _SEL_GATE + _CLR_ALL
    output = _ACT_G3

[sample]
    input  = _ACT_G
    gate   = _SELGP1_4 * _SEL_GATE + _CLR_ALL
    output = _ACT_G4

# variation
[switch]
    input1 = _VAR_G1
    input2 = _VAR_G2
    input3 = _VAR_G3
    input4 = _VAR_G4
    offset = _SEL_OFST
    output = _VAR_GS

[switch]
    input1  = _VAR_GS
    input2  = 0
    offset  = _CLR_TRIG
    output  = _VAR_G_SET

[encoder]
    select     = _GP1
    encoder    = E3.2
    color      = 0.3
    startvalue = _VAR_G_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _VAR_G

[sample]
    input  = _VAR_G
    gate   = _SELGP1_1 * _SEL_GATE + _CLR_ALL
    output = _VAR_G1

[sample]
    input  = _VAR_G
    gate   = _SELGP1_2 * _SEL_GATE + _CLR_ALL
    output = _VAR_G2

[sample]
    input  = _VAR_G
    gate   = _SELGP1_3 * _SEL_GATE + _CLR_ALL
    output = _VAR_G3

[sample]
    input  = _VAR_G
    gate   = _SELGP1_4 * _SEL_GATE + _CLR_ALL
    output = _VAR_G4

# dejavu
[switch]
    input1 = _DEJ_G1
    input2 = _DEJ_G2
    input3 = _DEJ_G3
    input4 = _DEJ_G4
    offset = _SEL_OFST
    output = _DEJ_GS

[switch]
    input1  = _DEJ_GS
    input2  = 1
    offset  = _CLR_TRIG
    output  = _DEJ_G_SET

[encoder]
    select     = _GP1
    encoder    = E3.3
    color      = 0.45
    startvalue = _DEJ_G_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _DEJ_G

[sample]
    input  = _DEJ_G
    gate   = _SELGP1_1 * _SEL_GATE + _CLR_ALL
    output = _DEJ_G1

[sample]
    input  = _DEJ_G
    gate   = _SELGP1_2 * _SEL_GATE + _CLR_ALL
    output = _DEJ_G2

[sample]
    input  = _DEJ_G
    gate   = _SELGP1_3 * _SEL_GATE + _CLR_ALL
    output = _DEJ_G3

[sample]
    input  = _DEJ_G
    gate   = _SELGP1_4 * _SEL_GATE + _CLR_ALL
    output = _DEJ_G4

# offbeat
[switch]
    input1 = _OFF_G1
    input2 = _OFF_G2
    input3 = _OFF_G3
    input4 = _OFF_G4
    offset = _SEL_OFST
    output = _OFF_GS

[switch]
    input1  = _OFF_GS
    input2  = 0.5
    offset  = _CLR_TRIG
    output  = _OFF_G_SET

[encoder]
    select     = _GP1
    encoder    = E3.4
    color      = 0.6
    notch      = 0.1
    startvalue = _OFF_G_SET
    clear      = _SEL_CNG + _CLR_TRIG
    output     = _OFF_G

[sample]
    input  = _OFF_G
    gate   = _SELGP1_1 * _SEL_GATE + _CLR_ALL
    output = _OFF_G1

[sample]
    input  = _OFF_G
    gate   = _SELGP1_2 * _SEL_GATE + _CLR_ALL
    output = _OFF_G2

[sample]
    input  = _OFF_G
    gate   = _SELGP1_3 * _SEL_GATE + _CLR_ALL
    output = _OFF_G3

[sample]
    input  = _OFF_G
    gate   = _SELGP1_4 * _SEL_GATE + _CLR_ALL
    output = _OFF_G4
    
