# performance mode selectors
[buttongroup]
    select    = _PERF_MDE
    minactive = 1
    maxactive = 1
    button1   = B2.17
    button2   = B2.18
    button3   = B2.19
    button4   = B2.20
    led1      = _PACT
    led2      = _PVAR
    led3      = _PFILL
    led4      = _PROLL
    longpress = _PMDE_SEL_LNG

[logic]
    input   = _PMDE_SEL_LNG
    negated = _PMDE_SEL_SHT

[copy]
    input  = _PACT * _PERF_MDE
    output = L2.17

[copy]
    input  = _PACT * _PERF_MDE
    output = L2.18

[copy]
    input  = _PACT * _PERF_MDE
    output = L2.19

[copy]
    input  = _PACT * _PERF_MDE
    output = L2.20

# clear on entering performance mode
# resets all the encoders to the current value of the individual algos
[logic]
    input1 = _MDE_SEL_CHANGE
    input2 = _PERF_MDE
    and    = _CLR_ON_PERF
    
# activity
[logic]
    input1 = _PMDE_SEL_SHT
    input2 = _PERF_MDE
    input2 = _PACT
    and    = _PACTG

[logic]
    input1 = _PMDE_SEL_LNG
    input2 = _PERF_MDE
    input2 = _PACT
    and    = _PACTCV
    
[logic]
    input1 = _PERF_MDE
    input2 = _PACTG
    and    = _CLR_PACTG
    
[logic]
    input1 = _PERF_MDE
    input2 = _PACTCV
    and    = _CLR_PACTCV

# activity encoders for gate algos
[encoder]
    select     = _SEL_1 * _PACTG
    encoder    = E3.1
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_G1
    clear      = B3.1 * _CLR_PACTG + _CLR_ON_PERF
    output     = _PACT_G1

[encoder]
    select     = _SEL_2 * _PACTG
    encoder    = E3.2
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_G2
    clear      = B3.2 * _CLR_PACTG + _CLR_ON_PERF
    output     = _PACT_G2

[encoder]
    select     = _SEL_3 * _PACTG
    encoder    = E3.3
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_G3
    clear      = B3.3 * _CLR_PACTG + _CLR_ON_PERF
    output     = _PACT_G3

[encoder]
    select     = _SEL_4 * _PACTG
    encoder    = E3.4
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_G4
    clear      = B3.4 * _CLR_PACTG + _CLR_ON_PERF
    output     = _PACT_G4

# activity encoders for CV algos
[encoder]
    select     = _SEL_1 * _PACTCV
    encoder    = E3.1
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_CV1
    clear      = B3.1 * _CLR_PACTCV + _CLR_ON_PERF
    output     = _PACT_CV1

[encoder]
    select     = _SEL_2 * _PACTCV
    encoder    = E3.2
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_CV2
    clear      = B3.2 * _CLR_PACTCV + _CLR_ON_PERF
    output     = _PACT_CV2

[encoder]
    select     = _SEL_3 * _PACTCV
    encoder    = E3.3
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_CV3
    clear      = B3.3 * _CLR_PACTCV + _CLR_ON_PERF
    output     = _PACT_CV3

[encoder]
    select     = _SEL_4 * _PACTCV
    encoder    = E3.4
    color      = 0.15
    notch      = 0.1
    startvalue = _NACT_CV4
    clear      = B3.4 * _CLR_PACTCV + _CLR_ON_PERF
    output     = _PACT_CV4

# variation
[logic]
    input1 = _PMDE_SEL_SHT
    input2 = _PERF_MDE
    input2 = _PVAR
    and    = _PVARG

[logic]
    input1 = _PMDE_SEL_LNG
    input2 = _PERF_MDE
    input2 = _PVAR
    and    = _PVARCV
    
[logic]
    input1 = _PERF_MDE
    input2 = _PVARG
    and    = _CLR_PVARG
    
[logic]
    input1 = _PERF_MDE
    input2 = _PVARCV
    and    = _CLR_PVARCV

# variation for gate algos
[encoder]
    select     = _SEL_1 * _PVARG
    encoder    = E3.1
    color      = 0.3
    startvalue = _NVAR_G1
    notch      = 0.1
    clear      = B3.1 * _CLR_PVARG + _CLR_ON_PERF
    output     = _PVAR_G1

[encoder]
    select     = _SEL_2 * _PVARG
    encoder    = E3.2
    color      = 0.3
    startvalue = _NVAR_G2
    notch      = 0.1
    clear      = B3.2 * _CLR_PVARG + _CLR_ON_PERF
    output     = _PVAR_G2

[encoder]
    select     = _SEL_3 * _PVARG
    encoder    = E3.3
    color      = 0.3
    startvalue = _NVAR_G3
    notch      = 0.1
    clear      = B3.3 * _CLR_PVARG + _CLR_ON_PERF
    output     = _PVAR_G3

[encoder]
    select     = _SEL_4 * _PVARG
    encoder    = E3.4
    color      = 0.3
    startvalue = _NVAR_G4
    notch      = 0.1
    clear      = B3.4 * _CLR_PVARG + _CLR_ON_PERF
    output     = _PVAR_G4

# variation for cv algos
[encoder]
    select     = _SEL_1 * _PVARCV
    encoder    = E3.1
    color      = 0.3
    startvalue = _NVAR_CV1
    notch      = 0.1
    clear      = B3.1 * _CLR_PVARCV + _CLR_ON_PERF
    output     = _PVAR_CV1

[encoder]
    select     = _SEL_2 * _PVARCV
    encoder    = E3.2
    color      = 0.3
    startvalue = _NVAR_CV2
    notch      = 0.1
    clear      = B3.2 * _CLR_PVARCV + _CLR_ON_PERF
    output     = _PVAR_CV2

[encoder]
    select     = _SEL_3 * _PVARCV
    encoder    = E3.3
    color      = 0.3
    startvalue = _NVAR_CV3
    notch      = 0.1
    clear      = B3.3 * _CLR_PVARCV + _CLR_ON_PERF
    output     = _PVAR_CV3

[encoder]
    select     = _SEL_4 * _PVARCV
    encoder    = E3.4
    color      = 0.3
    startvalue = _NVAR_CV4
    notch      = 0.1
    clear      = B3.4 * _CLR_PVARCV + _CLR_ON_PERF
    output     = _PVAR_CV4

# fill
[logic]
    input1 = _PMDE_SEL_SHT
    input2 = _PERF_MDE
    input2 = _PFILL
    and    = _PFILLG

[logic]
    input1 = _PMDE_SEL_LNG
    input2 = _PERF_MDE
    input2 = _PFILL
    and    = _PFILLCV
    
[logic]
    input1 = _PERF_MDE
    input2 = _PFILLG
    and    = _CLR_PFILLG
    
[logic]
    input1 = _PERF_MDE
    input2 = _PFILLCV
    and    = _CLR_PFILLCV

# fill for gate algos
[encoder]
    select     = _SEL_1 * _PFILLG
    encoder    = E3.1
    color      = 1.1
    startvalue = _NFILL_G1
    notch      = 0.1
    clear      = B3.1 * _CLR_PFILLG + _CLR_ON_PERF
    output     = _PFILL_G1

[encoder]
    select     = _SEL_2 * _PFILLG
    encoder    = E3.2
    color      = 1.1
    startvalue = _NFILL_G2
    notch      = 0.1
    clear      = B3.2 * _CLR_PFILLG + _CLR_ON_PERF
    output     = _PFILL_G2

[encoder]
    select     = _SEL_3 * _PFILLG
    encoder    = E3.3
    color      = 1.1
    startvalue = _NFILL_G3
    notch      = 0.1
    clear      = B3.3 * _CLR_PFILLG + _CLR_ON_PERF
    output     = _PFILL_G3

[encoder]
    select     = _SEL_4 * _PFILLG
    encoder    = E3.4
    color      = 1.1
    startvalue = _NFILL_G4
    notch      = 0.1
    clear      = B3.4 * _CLR_PFILLG + _CLR_ON_PERF
    output     = _PFILL_G4

# fill for cv algos
[encoder]
    select     = _SEL_1 * _PFILLCV
    encoder    = E3.1
    color      = 1.1
    startvalue = _NFILL_CV1
    notch      = 0.1
    clear      = B3.1 * _CLR_PFILLCV + _CLR_ON_PERF
    output     = _PFILL_CV1

[encoder]
    select     = _SEL_2 * _PFILLCV
    encoder    = E3.2
    color      = 1.1
    startvalue = _NFILL_CV2
    notch      = 0.1
    clear      = B3.2 * _CLR_PFILLCV + _CLR_ON_PERF
    output     = _PFILL_CV2

[encoder]
    select     = _SEL_3 * _PFILLCV
    encoder    = E3.3
    color      = 1.1
    startvalue = _NFILL_CV3
    notch      = 0.1
    clear      = B3.3 * _CLR_PFILLCV + _CLR_ON_PERF
    output     = _PFILL_CV3

[encoder]
    select     = _SEL_4 * _PFILLCV
    encoder    = E3.4
    color      = 1.1
    startvalue = _NFILL_CV4
    notch      = 0.1
    clear      = B3.4 * _CLR_PFILLCV + _CLR_ON_PERF
    output     = _PFILL_CV4

# rolls
[logic]
    input1 = _PMDE_SEL_SHT
    input2 = _PERF_MDE
    input2 = _PROLL
    and    = _PROLLG

[logic]
    input1 = _PMDE_SEL_LNG
    input2 = _PERF_MDE
    input2 = _PROLL
    and    = _PROLLCV
    
[logic]
    input1 = _PERF_MDE
    input2 = _PROLLG
    and    = _CLR_PROLLG
    
[logic]
    input1 = _PERF_MDE
    input2 = _PROLLCV
    and    = _CLR_PROLLCV

# roll for gate algos
[encoder]
    select     = _SEL_1 * _PROLLG
    encoder    = E3.1
    color      = 0.5
    startvalue = _NROLL_G1
    notch      = 0.1
    clear      = B3.1 * _CLR_PROLLG + _CLR_ON_PERF
    output     = _PROLL_G1

[encoder]
    select     = _SEL_2 * _PROLLG
    encoder    = E3.2
    color      = 0.5
    startvalue = _NROLL_G2
    notch      = 0.1
    clear      = B3.2 * _CLR_PROLLG + _CLR_ON_PERF
    output     = _PROLL_G2

[encoder]
    select     = _SEL_3 * _PROLLG
    encoder    = E3.3
    color      = 0.5
    startvalue = _NROLL_G3
    notch      = 0.1
    clear      = B3.3 * _CLR_PROLLG + _CLR_ON_PERF
    output     = _PROLL_G3

[encoder]
    select     = _SEL_4 * _PROLLG
    encoder    = E3.4
    color      = 0.5
    startvalue = _NROLL_G4
    notch      = 0.1
    clear      = B3.4 * _CLR_PROLLG + _CLR_ON_PERF
    output     = _PROLL_G4

# roll for CV algos
[encoder]
    select     = _SEL_1 * _PROLLCV
    encoder    = E3.1
    color      = 0.5
    startvalue = _NROLL_CV1
    notch      = 0.1
    clear      = B3.1 * _CLR_PROLLCV + _CLR_ON_PERF
    output     = _PROLL_CV1

[encoder]
    select     = _SEL_2 * _PROLLCV
    encoder    = E3.2
    color      = 0.5
    startvalue = _NROLL_CV2
    notch      = 0.1
    clear      = B3.2 * _CLR_PROLLCV + _CLR_ON_PERF
    output     = _PROLL_CV2

[encoder]
    select     = _SEL_3 * _PROLLCV
    encoder    = E3.3
    color      = 0.5
    startvalue = _NROLL_CV3
    notch      = 0.1
    clear      = B3.3 * _CLR_PROLLCV + _CLR_ON_PERF
    output     = _PROLL_CV3

[encoder]
    select     = _SEL_4 * _PROLLCV
    encoder    = E3.4
    color      = 0.5
    startvalue = _NROLL_CV4
    notch      = 0.1
    clear      = B3.4 * _CLR_PROLLCV + _CLR_ON_PERF
    output     = _PROLL_CV4

# change pattern buttons
[buttongroup]
    select    = _PERF_MDE
    button1   = B2.25
    button2   = B2.26
    button3   = B2.27
    button4   = B2.28
    led1      = _PTRN_G1
    led2      = _PTRN_G2
    led3      = _PTRN_G3
    led4      = _PTRN_G4
    longpress = _PTRNG_LNG

[logic]
    input   = _PTRNG_LNG
    negated = _PTRNG_SHT

[logic]
    input1 = _PTRN_G1
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G1

[logic]
    input1 = _PTRN_G1
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G1

[logic]
    input1 = _PTRN_G2
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G2

[logic]
    input1 = _PTRN_G2
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G2

[logic]
    input1 = _PTRN_G3
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G3

[logic]
    input1 = _PTRN_G3
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G3

[logic]
    input1 = _PTRN_G4
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G4

[logic]
    input1 = _PTRN_G4
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G4

[buttongroup]
    select    = _PERF_MDE
    button1   = B2.21
    button2   = B2.22
    button3   = B2.23
    button4   = B2.24
    led1      = _PTRN_CV1
    led2      = _PTRN_CV2
    led3      = _PTRN_CV3
    led4      = _PTRN_CV4
    longpress = _PTRNCV_LNG

[logic]
    input   = _PTRNCV_LNG
    negated = _PTRNCV_SHT

[logic]
    input1 = _PTRN_CV1
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV1

[logic]
    input1 = _PTRN_CV1
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV1

[logic]
    input1 = _PTRN_CV2
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV2

[logic]
    input1 = _PTRN_CV2
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV2

[logic]
    input1 = _PTRN_CV3
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV3

[logic]
    input1 = _PTRN_CV3
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV3

[logic]
    input1 = _PTRN_CV4
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV4

[logic]
    input1 = _PTRN_CV4
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV4
