# make algo leds turn of in perf mode
# this is just to make the interface cleaner
[buttongroup]
    select   = _PERF_MDE
    button1  = B2.1
    button2  = B2.2
    button3  = B2.3
    button4  = B2.4
    button5  = B2.5
    button6  = B2.6
    button7  = B2.7
    button8  = B2.8
    button9  = B2.9
    button10 = B2.10
    button11 = B2.11
    button12 = B2.12
    button13 = B2.13
    button14 = B2.14
    button15 = B2.15
    button16 = B2.16
    led1     = L2.1
    led2     = L2.2
    led3     = L2.3
    led4     = L2.4
    led5     = L2.5
    led6     = L2.6
    led7     = L2.7
    led8     = L2.8
    led9     = L2.9
    led10    = L2.10
    led11    = L2.11
    led12    = L2.12
    led13    = L2.13
    led14    = L2.14
    led15    = L2.15
    led16    = L2.16
    clear    = _CLR_ON_PERF

# performance mode selectors
[buttongroup]
    select      = _PERF_MDE
    minactive   = 1
    maxactive   = 1
    button1     = B2.17
    button2     = B2.18
    button3     = B2.19
    button4     = B2.20
    led1        = _PACT
    led2        = _PVAR
    led3        = _PFILL
    led4        = _PROLL
    output      = _PSEL_OFST
    longpress   = _PMDE_SEL_LNG
    buttonpress = _PSEL_CNG

[logic]
    input   = _PSEL_CNG
    negated = _PSEL_GATE

[logic]
    input   = _PMDE_SEL_LNG
    negated = _PMDE_SEL_SHT

[copy]
    input  = _PACT * _PERF_MDE
    output = L2.17

[copy]
    input  = _PVAR * _PERF_MDE
    output = L2.18

[copy]
    input  = _PFILL * _PERF_MDE
    output = L2.19

[copy]
    input  = _PROLL * _PERF_MDE
    output = L2.20

# clear on entering performance mode
# resets all the encoders to the current value of the individual algos
[logic]
    input1 = _MDE_SEL_CHANGE
    input2 = _PERF_MDE
    and    = _CLR_ON_PERF
    
# activity
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_SHT
    input2 = _PACTG
    and    = _SELPACTG
    
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_LNG
    input2 = _PACTCV
    and    = _SELPACTCV

# variation
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_SHT
    input2 = _PVARG
    and    = _SELPVARG
    
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_LNG
    input2 = _PVARCV
    and    = _SELPVARCV

# fill 
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_SHT
    input2 = _PFILLG
    and    = _SELPFILLG
    
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_LNG
    input2 = _PFILLCV
    and    = _SELPFILLCV

# roll
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_SHT
    input2 = _PROLLG
    and    = _SELPROLLG
    
[logic]
    input1 = _PERF_MDE * _PMDE_SEL_LNG
    input2 = _PROLLCV
    and    = _SELPROLLCV

[math]
    input1 = 2 * _PSEL_OFST
    input2 = 1 * _PMDE_SEL_LNG
    sum    = _OFST

[math]
    input1   = _PSEL_OFST + 1
    input2   = 2 * _PMDE_SEL_LNG
    multiply = _COL_MUL
    
# encoder1
# 0 2n + 1 = 1
# 1 2n + 1 = 3
# 2 2n + 1 = 5
# 3 2n + 1 = 7
    
[switch]
    input1 = _PACT_G1
    input2 = _PACT_CV1
    input3 = _PVAR_G1
    input4 = _PVAR_CV1
    input5 = _PFILL_G1
    input6 = _PFILL_CV1
    input7 = _PROLL_G1
    input8 = _PROLL_CV1
    offset = _OFST
    output = _ENC1_SET

[encoder]
    select     = _PERF_MDE
    encoder    = E3.1
    color      = 0.1 * _COL_MUL
    startvalue = _ENC1_SET
    clear      = _PSEL_CNG
    output     = _ENC1_OUT

[sample]
    input  = _ENC1_OUT
    gate   = _SELPACTG * _PSEL_GATE
    output = _PACT_G1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPVARG * _PSEL_GATE
    output = _PVAR_G1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPFILLG * _PSEL_GATE
    output = _PFILL_G1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPROLLG * _PSEL_GATE
    output = _PROLL_G1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPACTCV * _PSEL_GATE
    output = _PACT_CV1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPVARCV * _PSEL_GATE
    output = _PVAR_CV1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPFILLCV * _PSEL_GATE
    output = _PFILL_CV1

[sample]
    input  = _ENC1_OUT
    gate   = _SELPROLLCV * _PSEL_GATE
    output = _PROLL_CV1

# encoder 2    
[switch]
    input1 = _PACT_G2
    input2 = _PACT_CV2
    input3 = _PVAR_G2
    input4 = _PVAR_CV2
    input5 = _PFILL_G2
    input6 = _PFILL_CV2
    input7 = _PROLL_G2
    input8 = _PROLL_CV2
    offset = _OFST
    output = _ENC2_SET

[encoder]
    select     = _PERF_MDE
    encoder    = E3.2
    color      = 0.1 * _COL_MUL
    startvalue = _ENC2_SET
    clear      = _PSEL_CNG
    output     = _ENC2_OUT

[sample]
    input  = _ENC2_OUT
    gate   = _SELPACTG * _PSEL_GATE
    output = _PACT_G2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPVARG * _PSEL_GATE
    output = _PVAR_G2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPFILLG * _PSEL_GATE
    output = _PFILL_G2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPROLLG * _PSEL_GATE
    output = _PROLL_G2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPACTCV * _PSEL_GATE
    output = _PACT_CV2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPVARCV * _PSEL_GATE
    output = _PVAR_CV2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPFILLCV * _PSEL_GATE
    output = _PFILL_CV2

[sample]
    input  = _ENC2_OUT
    gate   = _SELPROLLCV * _PSEL_GATE
    output = _PROLL_CV2

# encoder 3  
[switch]
    input1 = _PACT_G3
    input2 = _PACT_CV3
    input3 = _PVAR_G3
    input4 = _PVAR_CV3
    input5 = _PFILL_G3
    input6 = _PFILL_CV3
    input7 = _PROLL_G3
    input8 = _PROLL_CV3
    offset = _OFST
    output = _ENC3_SET

[encoder]
    select     = _PERF_MDE
    encoder    = E3.3
    color      = 0.1 * _COL_MUL
    startvalue = _ENC3_SET
    clear      = _PSEL_CNG
    output     = _ENC3_OUT

[sample]
    input  = _ENC3_OUT
    gate   = _SELPACTG * _PSEL_GATE
    output = _PACT_G3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPVARG * _PSEL_GATE
    output = _PVAR_G3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPFILLG * _PSEL_GATE
    output = _PFILL_G3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPROLLG * _PSEL_GATE
    output = _PROLL_G3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPACTCV * _PSEL_GATE
    output = _PACT_CV3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPVARCV * _PSEL_GATE
    output = _PVAR_CV3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPFILLCV * _PSEL_GATE
    output = _PFILL_CV3

[sample]
    input  = _ENC3_OUT
    gate   = _SELPROLLCV * _PSEL_GATE
    output = _PROLL_CV3

# encoder 4
[switch]
    input1 = _PACT_G4
    input2 = _PACT_CV4
    input3 = _PVAR_G4
    input4 = _PVAR_CV4
    input5 = _PFILL_G4
    input6 = _PFILL_CV4
    input7 = _PROLL_G4
    input8 = _PROLL_CV4
    offset = _OFST
    output = _ENC4_SET

[encoder]
    select     = _PERF_MDE
    encoder    = E3.4
    color      = 0.1 * _COL_MUL
    startvalue = _ENC4_SET
    clear      = _PSEL_CNG
    output     = _ENC4_OUT

[sample]
    input  = _ENC4_OUT
    gate   = _SELPACTG * _PSEL_GATE
    output = _PACT_G4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPVARG * _PSEL_GATE
    output = _PVAR_G4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPFILLG * _PSEL_GATE
    output = _PFILL_G4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPROLLG * _PSEL_GATE
    output = _PROLL_G4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPACTCV * _PSEL_GATE
    output = _PACT_CV4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPVARCV * _PSEL_GATE
    output = _PVAR_CV4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPFILLCV * _PSEL_GATE
    output = _PFILL_CV4

[sample]
    input  = _ENC4_OUT
    gate   = _SELPROLLCV * _PSEL_GATE
    output = _PROLL_CV4

# change pattern buttons
[buttongroup]
    select    = _PERF_MDE
    button1   = B2.25
    button2   = B2.26
    button3   = B2.27
    button4   = B2.28
    led1      = _PTRN_G1
    led2      = _PTRN_G2
    led3      = _PTRN_G3
    led4      = _PTRN_G4
    longpress = _PTRNG_LNG

[logic]
    input   = _PTRNG_LNG
    negated = _PTRNG_SHT

[logic]
    input1 = _PTRN_G1
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G1

[logic]
    input1 = _PTRN_G1
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G1

[logic]
    input1 = _PTRN_G2
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G2

[logic]
    input1 = _PTRN_G2
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G2

[logic]
    input1 = _PTRN_G3
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G3

[logic]
    input1 = _PTRN_G3
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G3

[logic]
    input1 = _PTRN_G4
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_G4

[logic]
    input1 = _PTRN_G4
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_G4

[buttongroup]
    select    = _PERF_MDE
    button1   = B2.21
    button2   = B2.22
    button3   = B2.23
    button4   = B2.24
    led1      = _PTRN_CV1
    led2      = _PTRN_CV2
    led3      = _PTRN_CV3
    led4      = _PTRN_CV4
    longpress = _PTRNCV_LNG

[logic]
    input   = _PTRNCV_LNG
    negated = _PTRNCV_SHT

[logic]
    input1 = _PTRN_CV1
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV1

[logic]
    input1 = _PTRN_CV1
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV1

[logic]
    input1 = _PTRN_CV2
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV2

[logic]
    input1 = _PTRN_CV2
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV2

[logic]
    input1 = _PTRN_CV3
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV3

[logic]
    input1 = _PTRN_CV3
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV3

[logic]
    input1 = _PTRN_CV4
    input2 = _PTRNG_SHT
    and    = _PTRNG_FWD_CV4

[logic]
    input1 = _PTRN_CV4
    input2 = _PTRNG_LNG
    and    = _PTRNG_BCK_CV4
