# performance mode selectors
[buttongroup]
    select    = _PERF_MDE
    minactive = 1
    maxactive = 1
    button1   = B2.21
    led1      = _PACTG
    longpress = _PMDE_SEL_LNG

# clear on entering performance mode
# resets all the encoders to the current value of the individual algos
[logic]
    input1 = _MDE_SEL_CHANGE
    input2 = _PERF_MDE
    and    = _CLR_PERF_ACC
    
# activity
[logic]
    input1 = _PERF_MDE
    input2 = _PACTG
    and    = _CLR_PACTG

[logic]
    input1 = _PERF_MDE
    input2 = _PACTG
    input3 = _PMDE_SEL_LNG
    and    = _PACTCV
    
[logic]
    input1 = _PERF_MDE
    input2 = _PACTCV
    and    = _CLR_PACTCV

# activity encoders for gate algos
[encoder]
    select     = _SEL_1 * _PACTG
    encoder    = E3.1
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_G1
    clear      = B3.1 * _CLR_PACTG + _CLR_PERF_ACC
    output     = _PACT_G1

[encoder]
    select     = _SEL_2 * _PACTG
    encoder    = E3.2
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_G2
    clear      = B3.2 * _CLR_PACTG + _CLR_PERF_ACC
    output     = _PACT_G2

[encoder]
    select     = _SEL_3 * _PACTG
    encoder    = E3.3
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_G3
    clear      = B3.3 * _CLR_PACTG + _CLR_PERF_ACC
    output     = _PACT_G3

[encoder]
    select     = _SEL_4 * _PACTG
    encoder    = E3.4
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_G4
    clear      = B3.4 * _CLR_PACTG + _CLR_PERF_ACC
    output     = _PACT_G4

# activity encoders for CV algos
[encoder]
    select     = _SEL_1 * _PACTCV
    encoder    = E3.1
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_CV1
    clear      = B3.1 * _CLR_PACTCV + _CLR_PERF_ACC
    output     = _PACT_CV1

[encoder]
    select     = _SEL_2 * _PACTCV
    encoder    = E3.2
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_CV2
    clear      = B3.2 * _CLR_PACTCV + _CLR_PERF_ACC
    output     = _PACT_CV2

[encoder]
    select     = _SEL_3 * _PACTCV
    encoder    = E3.3
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_CV3
    clear      = B3.3 * _CLR_PACTCV + _CLR_PERF_ACC
    output     = _PACT_CV3

[encoder]
    select     = _SEL_4 * _PACTCV
    encoder    = E3.4
    color      = 0.15
    notch      = 0.1
    startvalue = _ACT_CV4
    clear      = B3.4 * _CLR_PACTCV + _CLR_PERF_ACC
    output     = _PACT_CV4

# variation
[encoder]
    select     = _GP1 * _SEL_1
    encoder    = E3.2
    color      = 0.3
    startvalue = 0
    clear      = B3.2 * _CLR_GP1_1 + _CLEAR_ALL
    output     = _VAR_G1

# fill
[encoder]
    select     = _GP3 * _SEL_1
    encoder    = E3.1
    color      = 1.1
    startvalue = 0
    clear      = B3.1 * _CLR_GP3_1 + _CLEAR_ALL
    output     = _FILL_G1

# rolls
[encoder]
    select     = _GP4 * _SEL_1
    encoder    = E3.1
    color      = 0.5
    startvalue = 0
    clear      = B3.1 * _CLR_GP4_1 + _CLEAR_ALL
    output     = _ROLL_G1
