
###############
# controllers #
###############
# controller initialization in order of appearance in rack
[p2b8]
[b32]
[e4]

#########
# clock #
#########
# setup clock and usage
# this is the internal clock set by P1.1
[pot]
    input       = P1.1
    output      = _RATE
    outputscale = 0.6	# change this to set 
    ledgauge    = on 	# set this to of to disable use of B32 leds as value gauge

[math]
   input1  = _RATE
   input2  = 40 / 600 # match quantization and bpm computation below (this is equal to 1 bpm)
   maximum = _RATE_C

# only allow 600 values per volt, to match the precision of bpm
# calculated backwards from lfo rate calculation below
# we have 4 PPQ -> 1 V / 600 = 0.00166.. * 40 = 0.06667hz * 15 = 1 bpm 
[quantizer]
    input  = _RATE_C
    steps  = 600
    output = _RATE_Q 

# 0 BPM to 360BPM at 16th notes. multiply by 10 to make into hz, then by 4 for 16th note resolution -> multiply by 6 for 24PPQ (standard eurorack clock)
# we have a range from 0.0 - 0.6 (see outputscale). 1 Hz = 60 bpm in quarter notes (1 pulse per second = 60 pulses per minute)
# so values here range from 0 to 24 Hz * 60 / 4 (or simply times 15) = 0 to 360 bpm in 4 pulses per quarter note (PPQ)
# this has to be converted to 24 PPQ for midiout as midi generally works on 24 PPQ
[lfo]
    hz = _RATE_Q * 40
    square = _INT_CLK

##########
#  MIDI  #
##########
[midiin]
    trs     = 1
    usb     = 1
    clock   = _MIDI_CLK # this is 4PPQ per definition
    running = _MIDI_RUN    

# forward any received midi info to trs1
[midithrough]
    fromusb = 1
    fromtrs = 1
    totrs   = 1

[midiout]
    trs     = 2
    usb     = 1
    clock   = _INT_CLK * 6 # 4 -> 24 PPQ

# use pot 2 of p2b8 for switching between midi and internal clock
# using discrete = 2 to limit values to integers 0 and 1
[pot]
    input    = P1.2
    discrete = 2 
    output   = _CLK_SEL

# either select internal or external clock
[switch]
    input1 = _INT_CLK
    input2 = _MIDI_CLK
    offset = _CLK_SEL
    output = _CLK

# use button 1 on p2b8 as play/pause incl. bpm indicator by flashing led
[flipflop]
    startvalue = 0
    toggle     = B1.1
    output     = _INT_RUN

# select run gate according to clock select
[switch]
    input1 = _MIDI_RUN
    input2 = _INT_RUN
    offset = _CLK_SEL
    output = _RUN
   
[select]
    select = _RUN
    input  = _CLK / 4 # set to 1PPQ aka flash on every beat
    output = L1.1
