# LABELS: master=18
[p2b8]
[b32]
[e4]

# ########
# clock #
# ########
# setup clock and usage
# this is the internal clock set by P1.1
[pot]
    pot = P1.1
    output = _RATE
    outputscale = 0.6 # change this to set
    ledgauge = on # set this to of to disable use of B32 leds as value gauge

[math]
    input1 = _RATE
    input2 = 40 / 600 # match quantization and bpm computation below (this is equal to 1 bpm)
    maximum = _RATE_C

# only allow 600 values per volt, to match the precision of bpm
# calculated backwards from lfo rate calculation below
# we have 4 PPQ -> 1 V / 600 = 0.00166.. * 40 = 0.06667hz * 15 = 1 bpm
[quantizer]
    input = _RATE_C
    steps = 600
    output = _RATE_Q

# 0 BPM to 360BPM at 16th notes. multiply by 10 to make into hz, then by 4 for 16th note resolution -> multiply by 6 for 24PPQ (standard eurorack clock)
# we have a range from 0.0 - 0.6 (see outputscale). 1 Hz = 60 bpm in quarter notes (1 pulse per second = 60 pulses per minute)
# so values here range from 0 to 24 Hz * 60 / 4 (or simply times 15) = 0 to 360 bpm in 4 pulses per quarter note (PPQ)
# this has to be converted to 24 PPQ for midiout as midi generally works on 24 PPQ
[lfo]
    hz = _RATE_Q * 40
    square = _INT_CLK

# #########
# MIDI  #
# #########
[midiin]
    trs = 1
    usb = 1
    clock = _MIDI_CLK # this is 4PPQ per definition
    running = _MIDI_RUN

# forward any received midi info to trs1
[midithrough]
    fromusb = 1
    fromtrs = 1
    totrs = 1

[midiout]
    trs = 2
    usb = 1
    clock = _INT_CLK * 6 # 4 -> 24 PPQ

# ################
# running setup #
# ################
# use pot 2 of p2b8 for switching between midi and internal clock
# using discrete = 2 to limit values to integers 0 and 1
[pot]
    pot = P1.2
    discrete = 2
    output = _CLK_SEL

# either select internal or external clock
[switch]
    input1 = _INT_CLK
    input2 = _MIDI_CLK
    offset = _CLK_SEL
    output1 = _CLK

# use button 1 on p2b8 as play/pause incl. bpm indicator by flashing led
# longpress to reset sequencers
[button]
    button = B1.1
    longpress = _RESET
    shortpress = _PLAY

# toggle between play and pause
[flipflop]
    startvalue = 0
    toggle = _PLAY
    output = _INT_RUN

# select run gate according to clock select
[switch]
    input1 = _MIDI_RUN
    input2 = _INT_RUN
    offset = _CLK_SEL
    output1 = _RUN

# display bpm as flashing L1.1 on p2b8
[select]
    select = _RUN
    input = _CLK / 4 # set to 1PPQ aka flash on every beat
    output = L1.1

# output 24 PPQ clock at O8
[copy]
    input = _CLK * 6 # scale to 24PPQ
    output = O8

#####################
# algoquencer setup #
#####################
# select mutes when on else usual track select
[button]
    button  = B1.3
    led     = L1.3
    output  = _MUTE_SEL
    negated = _TRACK_SEL

    
# select between the four available algoquencers
# second column of p2b8
[buttongroup]
    select  = _TRACK_SEL
    button1 = B1.2
    button2 = B1.4
    button3 = B1.6
    button4 = B1.8
    led1    = L1.2
    led2    = L1.4
    led3    = L1.6
    led4    = L1.8

[buttongroup]
    select    = _MUTE_SEL
    minactive = 0
    maxactive = 4
    button1   = B1.2
    button2   = B1.4
    button3   = B1.6
    button4   = B1.8
    led1      = L1.2
    led2      = L1.4
    led3      = L1.6
    led4      = L1.8
