# LABELS: master=18
[p2b8]
[b32]
[e4]

#########
# clock #
#########
# setup clock and usage for 30 - 240 bpm
# this is the internal clock set by P1.1
[pot]
    pot         = P1.1
    output      = _RATE
    ledgauge    = off

# we want 1 bpm per step so we need 240 - 30  = 210 steps
[quantizer]
    input  = _RATE
    steps  = 210
    output = _RATE_Q

# here we want 30 to 240 BPM at 16th note resolution
# convert bpm to Hz by dividing by 15 (this is divide by 60 to go from bpm to bps and then multiply by 4 to get 4PPQ)
# -> 240 BPM = 16Hz; 30 BPM = 2Hz so we need to go from 2 to 16Hz
# this means we need to scale _CLK_RATE by a factor of 14Hz / 1V = 14
[lfo]
    hz     = _RATE_Q * 14 + 2
    square = _INT_CLK

# 24PPQ clock
[clocktool]
   clock    = _INT_CLK
   output   = _INT_CLK_24
   multiply = 6

########
# MIDI #
########
[midiin]
    trs        = 1
    usb        = 1
    clock      = _MIDI_CLK    # this is 4PPQ per definition
    midiclock  = _MIDI_CLK_24
    running    = _MIDI_RUN

# forward any received midi info to trs1
[midithrough]
    fromusb = 1
    fromtrs = 1
    totrs   = 1

[midiout]
    trs   = 2
    usb   = 1
    clock = _INT_CLK

#################
# running setup #
#################
# use pot 2 of p2b8 for switching between midi and internal clock
# using discrete = 2 to limit values to integers 0 and 1
[pot]
    pot      = P1.2
    discrete = 2
    output   = _CLK_SEL
    ledgauge = off

# either select internal or external clock
[switch]
    input1  = _INT_CLK
    input2  = _MIDI_CLK
    offset  = _CLK_SEL
    output1 = _MASTER_CLK

# use button 1 on p2b8 as play/pause incl. bpm indicator by flashing led
# longpress to reset sequencers
[button]
    button     = B1.1
    led        = L1.1
    onvalue    = _MASTER_CLK
    offvalue   = 0
    output     = _CLK
    longpress  = _RESET
    
# output selected clock
[switch]
    input1 = _INT_CLK_24
    input2 = _MIDI_CLK_24
    offset = _CLK_SEL
    output = O8

# select output run
[switch]
    input1 = L1.1
    input2 = _MIDI_RUN
    offset = _CLK_SEL
    output = O6

########################
# algoquencer controls #
########################
# select mutes when on else usual track select
[button]
    button  = B1.3
    led     = L1.3
    output  = _MUTE_SEL
    negated = _TRACK_SEL

[button]
    button  = B1.5
    led     = L1.5
    output  = _LEN_SEL

# select encoderbanks
[buttongroup]
    maxactive = 1
    button1   = B1.2
    button2   = B1.4
    button3   = B1.6
    button4   = B1.8
    led1      = L1.2
    led2      = L1.4
    led3      = L1.6
    led4      = L1.8

# activity
[encoderbank]
    select       = L1.2
    firstencoder = E3.1
    color        = 0.2
    notch        = 0.1
    output1      = _ACT_1
    output2      = _ACT_2
    output3      = _ACT_3
    output4      = _ACT_4

# variation
[encoderbank]
    select       = L1.4
    firstencoder = E3.1
    color        = 0.6
    notch        = 0.1
    output1      = _VAR_1
    output2      = _VAR_2
    output3      = _VAR_3
    output4      = _VAR_4

# dejavu
[encoderbank]
    select       = L1.6
    firstencoder = E3.1
    color        = 0.8
    notch        = 0.1
    output1      = _DEJ_1
    output2      = _DEJ_2
    output3      = _DEJ_3
    output4      = _DEJ_4

# offbeats
[encoderbank]
    select       = L1.8
    firstencoder = E3.1
    color        = 1
    notch        = 0.1
    output1      = _OFF_1
    output2      = _OFF_2
    output3      = _OFF_3
    output4      = _OFF_4

# select between the four available algoquencers
# second column of p2b8
[buttongroup]
    select    = _TRACK_SEL
    minactive = 1
    maxactive = 4
    button1   = B2.29
    button2   = B2.30
    button3   = B2.31
    button4   = B2.32
    led1      = _SEL_1
    led2      = _SEL_2
    led3      = _SEL_3
    led4      = _SEL_4

# allow reroll only in track select mode
[logic]
    input1 = _TRACK_SEL
    input2 = B1.7
    and    = _REROLL

#####################
# algoquencer setup #
#####################
# track 1
[algoquencer]
    select       = _SEL_1
    clock        = _CLK
    reset        = _RESET
    mutebutton   = B2.29 * _MUTE_SEL
    muteled      = _MUTE_LED_1
    lengthbutton = _SEL_1 * _LEN_SEL
    activity     = _ACT_1
    variation    = _VAR_1
    dejavu       = _DEJ_1
    offbeats     = _OFF_1
    reroll       = _REROLL * _SEL_1
    gate         = G1
    pitch        = O1
    button1    = B2.1
    button2    = B2.2
    button3    = B2.3
    button4    = B2.4
    button5    = B2.5
    button6    = B2.6
    button7    = B2.7
    button8    = B2.8
    button9    = B2.9
    button10   = B2.10
    button11   = B2.11
    button12   = B2.12
    button13   = B2.13
    button14   = B2.14
    button15   = B2.15
    button16   = B2.16
    led1       = L2.1
    led2       = L2.2
    led3       = L2.3
    led4       = L2.4
    led5       = L2.5
    led6       = L2.6
    led7       = L2.7
    led8       = L2.8
    led9       = L2.9
    led10      = L2.10
    led11      = L2.11
    led12      = L2.12
    led13      = L2.13
    led14      = L2.14
    led15      = L2.15
    led16      = L2.16

[switch]
    offset  = _SEL_1
    input1  = _MUTE_LED_1 * 0.2
    input2  = 1.0
    output1 = _LED_1

[switch]
    offset  = _MUTE_SEL
    input1  = _LED_1
    input2  = _MUTE_LED_1
    output1 = L2.29

# track 2
[algoquencer]
    select       = _SEL_2
    clock        = _CLK
    reset        = _RESET
    mutebutton   = B2.30 * _MUTE_SEL
    muteled      = _MUTE_LED_2
    lengthbutton = _SEL_2 * _LEN_SEL
    activity     = _ACT_2
    variation    = _VAR_2
    dejavu       = _DEJ_2
    offbeats     = _OFF_2
    reroll       = _REROLL * _SEL_2
    gate         = G2
    pitch        = O3
    button1    = B2.1
    button2    = B2.2
    button3    = B2.3
    button4    = B2.4
    button5    = B2.5
    button6    = B2.6
    button7    = B2.7
    button8    = B2.8
    button9    = B2.9
    button10   = B2.10
    button11   = B2.11
    button12   = B2.12
    button13   = B2.13
    button14   = B2.14
    button15   = B2.15
    button16   = B2.16
    led1       = L2.1
    led2       = L2.2
    led3       = L2.3
    led4       = L2.4
    led5       = L2.5
    led6       = L2.6
    led7       = L2.7
    led8       = L2.8
    led9       = L2.9
    led10      = L2.10
    led11      = L2.11
    led12      = L2.12
    led13      = L2.13
    led14      = L2.14
    led15      = L2.15
    led16      = L2.16

[switch]
    offset  = _SEL_2
    input1  = _MUTE_LED_2 * 0.2
    input2  = 1.0
    output1 = _LED_2
    
[switch]
    offset  = _MUTE_SEL
    input1  = _LED_2
    input2  = _MUTE_LED_2
    output1 = L2.30

# track 3
[algoquencer]
    select       = _SEL_3
    clock        = _CLK
    reset        = _RESET
    mutebutton   = B2.31 * _MUTE_SEL
    muteled      = _MUTE_LED_3
    lengthbutton = _SEL_3 * _LEN_SEL
    activity     = _ACT_3
    variation    = _VAR_3
    dejavu       = _DEJ_3
    offbeats     = _OFF_3
    reroll       = _REROLL * _SEL_3
    gate         = G3
    pitch        = O5
    button1    = B2.1
    button2    = B2.2
    button3    = B2.3
    button4    = B2.4
    button5    = B2.5
    button6    = B2.6
    button7    = B2.7
    button8    = B2.8
    button9    = B2.9
    button10   = B2.10
    button11   = B2.11
    button12   = B2.12
    button13   = B2.13
    button14   = B2.14
    button15   = B2.15
    button16   = B2.16
    led1       = L2.1
    led2       = L2.2
    led3       = L2.3
    led4       = L2.4
    led5       = L2.5
    led6       = L2.6
    led7       = L2.7
    led8       = L2.8
    led9       = L2.9
    led10      = L2.10
    led11      = L2.11
    led12      = L2.12
    led13      = L2.13
    led14      = L2.14
    led15      = L2.15
    led16      = L2.16

[switch]
    offset  = _SEL_3
    input1  = _MUTE_LED_3 * 0.2
    input2  = 1.0
    output1 = _LED_3
    
[switch]
    offset  = _MUTE_SEL
    input1  = _LED_3
    input2  = _MUTE_LED_3
    output1 = L2.31

# track 4
[algoquencer]
    select       = _SEL_4
    clock        = _CLK
    reset        = _RESET
    mutebutton   = B2.32 * _MUTE_SEL
    muteled      = _MUTE_LED_4
    lengthbutton = _SEL_4 * _LEN_SEL 
    activity     = _ACT_4
    variation    = _VAR_4
    dejavu       = _DEJ_4
    offbeats     = _OFF_4
    reroll       = _REROLL * _SEL_4   
    gate         = G4
    pitch        = O7
    button1    = B2.1
    button2    = B2.2
    button3    = B2.3
    button4    = B2.4
    button5    = B2.5
    button6    = B2.6
    button7    = B2.7
    button8    = B2.8
    button9    = B2.9
    button10   = B2.10
    button11   = B2.11
    button12   = B2.12
    button13   = B2.13
    button14   = B2.14
    button15   = B2.15
    button16   = B2.16
    led1       = L2.1
    led2       = L2.2
    led3       = L2.3
    led4       = L2.4
    led5       = L2.5
    led6       = L2.6
    led7       = L2.7
    led8       = L2.8
    led9       = L2.9
    led10      = L2.10
    led11      = L2.11
    led12      = L2.12
    led13      = L2.13
    led14      = L2.14
    led15      = L2.15
    led16      = L2.16

[switch]
    offset  = _SEL_4
    input1  = _MUTE_LED_4 * 0.2
    input2  = 1.0
    output1 = _LED_4

[switch]
    offset  = _MUTE_SEL
    input1  = _LED_4
    input2  = _MUTE_LED_4
    output1 = L2.32
